package wurmcraft.wurmatron.common.utils.thaumcraft;

import com.bioxx.tfc.api.TFCBlocks;
import com.bioxx.tfc.api.TFCItems;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;

import java.util.Arrays;

public class TAspect {

		public TAspect (ItemStack stack, AspectList aspects) {
				ThaumcraftApi.objectTags.put(Arrays.asList(stack.getItem(), stack.getItemDamage()), aspects);
		}

		public static void addAspects () {
				int Wild = OreDictionary.WILDCARD_VALUE;
				new TAspect(new ItemStack(TFCItems.bismuthIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.tinIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.zincIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.copperIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.bronzeIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.blackBronzeIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.brassIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.leadIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.goldIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.roseGoldIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.silverIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.sterlingSilverIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.platinumIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.wroughtIronIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.nickelIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.pigIronIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.redSteelIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.blueSteelIngot), new AspectList().add(Aspect.METAL, 4));
				new TAspect(new ItemStack(TFCItems.highCarbonBlackSteelIngot), new AspectList().add(Aspect.METAL, 4).add(Aspect.FIRE, 2));
				new TAspect(new ItemStack(TFCItems.highCarbonSteelIngot), new AspectList().add(Aspect.METAL, 4).add(Aspect.FIRE, 2));
				new TAspect(new ItemStack(TFCItems.highCarbonBlueSteelIngot), new AspectList().add(Aspect.METAL, 4).add(Aspect.FIRE, 2));
				new TAspect(new ItemStack(TFCItems.weakBlueSteelIngot), new AspectList().add(Aspect.METAL, 4).add(Aspect.FIRE, 2));
				new TAspect(new ItemStack(TFCItems.weakRedSteelIngot), new AspectList().add(Aspect.METAL, 4).add(Aspect.FIRE, 2));
				new TAspect(new ItemStack(TFCItems.weakSteelIngot), new AspectList().add(Aspect.METAL, 4).add(Aspect.FIRE, 2));
				new TAspect(new ItemStack(TFCItems.bismuthSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.tinSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.zincSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.copperSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.bronzeSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.blackBronzeSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.brassSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.leadSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.goldSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.roseGoldSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.silverSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.sterlingSilverSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.platinumSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.wroughtIronSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.nickelSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.pigIronSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.redSteelSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.blueSteelSheet), new AspectList().add(Aspect.METAL, 8));
				new TAspect(new ItemStack(TFCItems.arrow), new AspectList().add(Aspect.MOTION, 2).add(Aspect.TOOL, 4));
				new TAspect(new ItemStack(TFCItems.yellowBellPepper), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.wintergreenBerry), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.wheatWhole), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.snowberry), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.strawberry), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.squash), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.tomato), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.redApple), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.greenApple), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.redBellPepper), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.blackberry), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.blueberry), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCItems.carrot), new AspectList().add(Aspect.FLESH, 8).add(Aspect.HUNGER, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 0), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 1), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 2), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 3), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 4), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 5), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 6), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil, 1, 7), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil2, 1, 0), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil2, 1, 1), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.anvil2, 1, 2), new AspectList().add(Aspect.CRAFT, 8).add(Aspect.ARMOR, 4));
				new TAspect(new ItemStack(TFCBlocks.blastFurnace, 1, 0), new AspectList().add(Aspect.MECHANISM, 24).add(Aspect.ARMOR, 12).add(Aspect.METAL, 24));
				new TAspect(new ItemStack(TFCBlocks.bloomery, 1, 0), new AspectList().add(Aspect.MECHANISM, 16).add(Aspect.ARMOR, 8).add(Aspect.METAL, 16));
				new TAspect(new ItemStack(TFCBlocks.grass, 1, Wild), new AspectList().add(Aspect.EARTH, 8));
				new TAspect(new ItemStack(TFCBlocks.grass2, 1, Wild), new AspectList().add(Aspect.EARTH, 8));
				new TAspect(new ItemStack(TFCBlocks.dirt, 1, Wild), new AspectList().add(Aspect.EARTH, 8));
				new TAspect(new ItemStack(TFCBlocks.dirt2, 1, Wild), new AspectList().add(Aspect.EARTH, 8));
				new TAspect(new ItemStack(TFCBlocks.dryGrass, 1, Wild), new AspectList().add(Aspect.EARTH, 10));
				new TAspect(new ItemStack(TFCBlocks.dryGrass2, 1, Wild), new AspectList().add(Aspect.EARTH, 10));
				new TAspect(new ItemStack(TFCBlocks.clayGrass, 1, Wild), new AspectList().add(Aspect.EARTH, 8).add(Aspect.WATER, 4));
				new TAspect(new ItemStack(TFCBlocks.clayGrass2, 1, Wild), new AspectList().add(Aspect.EARTH, 8).add(Aspect.WATER, 4));
				new TAspect(new ItemStack(TFCBlocks.bellows, 1, Wild), new AspectList().add(Aspect.MOTION, 12).add(Aspect.MECHANISM, 4));
				new TAspect(new ItemStack(TFCBlocks.planks, 1, Wild), new AspectList().add(Aspect.TREE, 10));
				new TAspect(new ItemStack(TFCBlocks.planks2, 1, Wild), new AspectList().add(Aspect.TREE, 10));
				new TAspect(new ItemStack(TFCBlocks.stoneIgEx, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneIgExBrick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneIgExSmooth, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneIgIn, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneIgInBrick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneIgInCobble, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneIgInSmooth, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneMM, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneMMBrick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneMMCobble, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneMMSmooth, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneSed, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneSedBrick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneSedCobble, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.stoneSedSmooth, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 2));
				new TAspect(new ItemStack(TFCBlocks.metalSheet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10));
				new TAspect(new ItemStack(TFCItems.copperAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.copperAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.copperBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.copperChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.copperChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.copperGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.copperHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.copperHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.copperHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.copperHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.copperJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperPick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperPickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.copperSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.bronzeAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.bronzeAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.bronzeBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bronzeChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.bronzeChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.bronzeGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bronzeHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.bronzeHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.bronzeHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bronzeHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bronzeJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzePick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzePickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bronzeSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.blackBronzeAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.blackBronzeAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.blackBronzeBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackBronzeChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.blackBronzeChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.blackBronzeGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackBronzeHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.blackBronzeHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.blackBronzeHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackBronzeHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackBronzeJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzePick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzePickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackBronzeSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzePick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzePickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.bismuthBronzeSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.wroughtIronAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.wroughtIronAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.wroughtIronBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.wroughtIronChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.wroughtIronChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.wroughtIronGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.wroughtIronHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.wroughtIronHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.wroughtIronHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.wroughtIronHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.wroughtIronJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronPick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronPickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.wroughtIronSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.steelAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.steelAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.steelBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.steelChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.steelChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.steelGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.steelHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.steelHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.steelHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.steelHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.steelJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelPick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelPickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.steelSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.blackSteelAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.blackSteelAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.blackSteelBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackSteelChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.blackSteelChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.blackSteelGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackSteelHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.blackSteelHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.blackSteelHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackSteelHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blackSteelJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelPick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelPickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blackSteelSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.redSteelAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.redSteelAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.redSteelBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.redSteelChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.redSteelChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.redSteelGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.redSteelHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.redSteelHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.redSteelHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.redSteelHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.redSteelJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelPick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelPickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.redSteelSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
				new TAspect(new ItemStack(TFCItems.blueSteelAxe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.blueSteelAxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
				new TAspect(new ItemStack(TFCItems.blueSteelBoots, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelChestplate, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blueSteelChisel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.blueSteelChiselHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 12).add(Aspect.TOOL, 8));
				new TAspect(new ItemStack(TFCItems.blueSteelGreaves, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blueSteelHammer, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelHammerHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 21).add(Aspect.TOOL, 11));
				new TAspect(new ItemStack(TFCItems.blueSteelHelmet, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 22).add(Aspect.TOOL, 15));
				new TAspect(new ItemStack(TFCItems.blueSteelHoe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 25).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blueSteelHoeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 20).add(Aspect.TOOL, 12));
				new TAspect(new ItemStack(TFCItems.blueSteelJavelin, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelJavelinHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelKnife, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelKnifeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelMace, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelMaceHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelPick, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelPickaxeHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelProPickHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelSaw, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelSawHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelScythe, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelScytheHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelShovel, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelSword, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10));
				new TAspect(new ItemStack(TFCItems.blueSteelSwordHead, 1, Wild), new AspectList().add(Aspect.ENTROPY, 4).add(Aspect.METAL, 10).add(Aspect.TOOL, 10).add(Aspect.WEAPON, 8));
		}
}