package wurmcraft.wurmatron.common.items;

import com.bioxx.tfc.api.Enums.EnumFoodGroup;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.util.EnumHelper;

import java.util.ArrayList;
import java.util.HashMap;

public class WTItems {

		public static ArrayList<String> itemMaterialNames = new ArrayList<String>();
		public static ArrayList<String> itemSpecialNames = new ArrayList<String>();
		public static ArrayList<String> itemBasicFoodNames = new ArrayList<String>();
		public static ArrayList<String> itemPillNames = new ArrayList<String>();
		public static ArrayList<String> itemClumpNames = new ArrayList<String>();
		public static ArrayList<String> itemCrystalNames = new ArrayList<String>();
		public static ArrayList<String> itemShardNames = new ArrayList<String>();
		public static ArrayList<String> itemDirtyNames = new ArrayList<String>();
		public static ArrayList<String> itemCastNames = new ArrayList<String>();
		public static ArrayList<String> itemMetalCastNames = new ArrayList<String>();
		public static ArrayList<String> itemTokenNames = new ArrayList<String>();

		public static HashMap<String, EnumChatFormatting> itemSpecialColors = new HashMap<String, EnumChatFormatting>();
		public static HashMap<String, EnumFoodGroup[]> itemBasicFoodGroups = new HashMap<String, EnumFoodGroup[]>();
		public static HashMap<String, EnumFoodGroup[]> itemPillFoodGroups = new HashMap<String, EnumFoodGroup[]>();
		public static HashMap<String, EnumChatFormatting> itemTokenColors = new HashMap<String, EnumChatFormatting>();

		public static Item itemMaterial;
		public static Item itemSpecial;
		public static Item itemBasicFood;
		public static Item itemPill;
		public static ItemWaterJug itemJug_2;
		public static ItemWaterJug itemJug_4;
		public static ItemWaterJug itemJug_6;
		public static ItemWaterJug itemJug_12;
		public static ItemWaterJug itemJug_24;
		public static ItemWaterJug itemJug_48;
		public static Item itemCast;
		public static Item itemMetalCast;
		public static Item itemToken;
		// Credits
		public static Item creditBismuth;
		public static Item creditCopper;
		public static Item creditGold;
		public static Item creditIron;
		public static Item creditLead;
		public static Item creditNickel;
		public static Item creditPlatinum;
		public static Item creditSilver;
		public static Item creditTin;
		public static Item creditZinc;
		// Processing Items
		public static Item itemClump;
		public static Item itemCrystal;
		public static Item itemShard;
		public static Item itemDirty;
		// Dark Matter
		public static Item helmetDarkMatter;
		public static Item chestDarkMatter;
		public static Item leggsDarkMatter;
		public static Item bootsDarkMatter;
		public static final ItemArmor.ArmorMaterial DARKMATTER = EnumHelper.addArmorMaterial("DARKMATTER", -1, new int[] {90, 90, 90, 90}, 500);
		// Red Matter
		public static Item helmetRedMatter;
		public static Item chestRedMatter;
		public static Item leggsRedMatter;
		public static Item bootsRedMatter;
		public static final ItemArmor.ArmorMaterial REDMATTER = EnumHelper.addArmorMaterial("REDMATTER", -1, new int[] {90, 90, 90, 90}, 500);

		public static void registerItems () {
				itemMaterialNames.add("solarCore");
				itemMaterialNames.add("craftingCore");
				itemMaterialNames.add("greenSteel");
				itemMaterialNames.add("energyReactor");
				itemMaterialNames.add("mixedSheet");
				itemMaterialNames.add("pinkSteel");
				itemMaterialNames.add("yellowSteel");
				itemMaterialNames.add("orangeSteel");
				itemMaterialNames.add("purpleSteel");
				itemMaterialNames.add("cyanSteel");
				itemMaterialNames.add("brownSteel");
				itemMaterialNames.add("graySteel");
				itemMaterialNames.add("rainbowSteel");
				itemMaterialNames.add("magicChunk");
				itemMaterialNames.add("quantumCore");
				itemMaterialNames.add("quantumSingularity");
				itemMaterialNames.add("quantumFoam");
				itemMaterialNames.add("halfium");
				itemMaterialNames.add("titanium");
				itemMaterialNames.add("francium");
				itemMaterialNames.add("autocore");
				itemMaterialNames.add("radiationShielding");
				itemMaterialNames.add("stableMagicEssence");
				itemMaterialNames.add("bloodInfused");
				itemMaterialNames.add("natureCore");
				itemMaterialNames.add("natureCoreMK2");
				itemMaterialNames.add("antimatter");
				itemMaterialNames.add("engineCoil");
				itemMaterialNames.add("quarryCore");
				itemMaterialNames.add("gearMixedSheet");
				itemMaterialNames.add("miningCore");
				itemMaterialNames.add("refiningModule");
				itemMaterialNames.add("computationalCore");
				itemMaterialNames.add("machineFrame");
				itemMaterialNames.add("spaceModule");
				itemMaterialNames.add("unstableMatter");
				itemMaterialNames.add("jetpackParts");
				itemMaterialNames.add("electroMagneticShielding");
				itemMaterialNames.add("electroShielding");
				itemMaterialNames.add("wandParts");
				itemMaterialNames.add("pumpkinBits");
				//itemMaterialNames.add("sheetCat");
				registerItem(itemMaterial = new ItemMaterial(itemMaterialNames, "itemMaterial"), "itemMaterial");
				itemSpecialColors.put("creativeParts", EnumChatFormatting.DARK_PURPLE);
				itemSpecialColors.put("redMatter", EnumChatFormatting.DARK_RED);
				itemSpecialColors.put("darkMatter", EnumChatFormatting.DARK_PURPLE);
				itemSpecialColors.put("creativePartsEnergy", EnumChatFormatting.DARK_PURPLE);
				itemSpecialNames.add("darkMatter");
				itemSpecialNames.add("redMatter");
				itemSpecialNames.add("creativeParts");
				itemSpecialNames.add("creativePartsEnergy");
				registerItem(itemSpecial = new ItemSpecial(itemSpecialNames, itemSpecialColors).setUnlocalizedName("itemSpecial"), "itemSpecial");
				itemBasicFoodGroups.put("foodFruit", new EnumFoodGroup[] {EnumFoodGroup.Fruit});
				itemBasicFoodGroups.put("foodGrain", new EnumFoodGroup[] {EnumFoodGroup.Grain});
				itemBasicFoodGroups.put("foodProtein", new EnumFoodGroup[] {EnumFoodGroup.Protein});
				itemBasicFoodGroups.put("foodVegetable", new EnumFoodGroup[] {EnumFoodGroup.Vegetable});
				itemBasicFoodGroups.put("foodDairy", new EnumFoodGroup[] {EnumFoodGroup.Dairy});
				itemBasicFoodGroups.put("humanSoul", new EnumFoodGroup[] {EnumFoodGroup.Protein});
				itemBasicFoodGroups.put("melonBread", new EnumFoodGroup[] {EnumFoodGroup.Grain});
				itemBasicFoodGroups.put("galaxyBaggel", new EnumFoodGroup[] {EnumFoodGroup.Grain, EnumFoodGroup.Dairy});
				itemBasicFoodGroups.put("deathMelon", new EnumFoodGroup[] {EnumFoodGroup.Grain, EnumFoodGroup.Grain});
				itemBasicFoodGroups.put("wurm", new EnumFoodGroup[] {EnumFoodGroup.Grain, EnumFoodGroup.Fruit, EnumFoodGroup.Protein, EnumFoodGroup.Vegetable, EnumFoodGroup.Dairy});
				itemBasicFoodNames.add("foodFruit");
				itemBasicFoodNames.add("foodGrain");
				itemBasicFoodNames.add("foodProtein");
				itemBasicFoodNames.add("foodVegetable");
				itemBasicFoodNames.add("foodDairy");
				itemBasicFoodNames.add("humanSoul");
				itemBasicFoodNames.add("melonBread");
				itemBasicFoodNames.add("galaxyBaggel");
				itemBasicFoodNames.add("deathMelon");
				itemBasicFoodNames.add("wurm");
				registerItem(itemBasicFood = new ItemBasicTFCFood(itemBasicFoodNames, itemBasicFoodGroups), "iemBasicFood");
				itemPillFoodGroups.put("pillFruit", new EnumFoodGroup[] {EnumFoodGroup.Fruit});
				itemPillFoodGroups.put("pillGrain", new EnumFoodGroup[] {EnumFoodGroup.Grain});
				itemPillFoodGroups.put("pillProtein", new EnumFoodGroup[] {EnumFoodGroup.Protein});
				itemPillFoodGroups.put("pillVegetable", new EnumFoodGroup[] {EnumFoodGroup.Vegetable});
				itemPillFoodGroups.put("pillDairy", new EnumFoodGroup[] {EnumFoodGroup.Dairy});
				itemPillFoodGroups.put("pillAll", new EnumFoodGroup[] {EnumFoodGroup.Dairy, EnumFoodGroup.Fruit, EnumFoodGroup.Grain, EnumFoodGroup.Protein, EnumFoodGroup.Vegetable});
				itemPillNames.add("pillFruit");
				itemPillNames.add("pillGrain");
				itemPillNames.add("pillProtein");
				itemPillNames.add("pillVegetable");
				itemPillNames.add("pillDairy");
				itemPillNames.add("pillAll");
				registerItem(itemPill = new ItemPill(itemPillNames, itemPillFoodGroups), "itemPill");
				itemClumpNames.add("clumpBismuth");
				itemClumpNames.add("clumpCopper");
				itemClumpNames.add("clumpGold");
				itemClumpNames.add("clumpIron");
				itemClumpNames.add("clumpLead");
				itemClumpNames.add("clumpNickel");
				itemClumpNames.add("clumpPlatinum");
				itemClumpNames.add("clumpSilver");
				itemClumpNames.add("clumpTin");
				itemClumpNames.add("clumpZinc");
				registerItem(itemClump = new ItemClump(itemClumpNames), "itemClump");
				itemCrystalNames.add("crystalBismuth");
				itemCrystalNames.add("crystalCopper");
				itemCrystalNames.add("crystalGold");
				itemCrystalNames.add("crystalIron");
				itemCrystalNames.add("crystalLead");
				itemCrystalNames.add("crystalNickel");
				itemCrystalNames.add("crystalPlatinum");
				itemCrystalNames.add("crystalSilver");
				itemCrystalNames.add("crystalTin");
				itemCrystalNames.add("crystalZinc");
				registerItem(itemCrystal = new ItemCrystal(itemCrystalNames), "itemCrystal");
				itemShardNames.add("shardBismuth");
				itemShardNames.add("shardCopper");
				itemShardNames.add("shardGold");
				itemShardNames.add("shardIron");
				itemShardNames.add("shardLead");
				itemShardNames.add("shardNickel");
				itemShardNames.add("shardPlatinum");
				itemShardNames.add("shardSilver");
				itemShardNames.add("shardTin");
				itemShardNames.add("shardZinc");
				registerItem(itemShard = new ItemShard(itemShardNames), "itemShard");
				itemDirtyNames.add("dirtyBismuth");
				itemDirtyNames.add("dirtyCopper");
				itemDirtyNames.add("dirtyGold");
				itemDirtyNames.add("dirtyIron");
				itemDirtyNames.add("dirtyLead");
				itemDirtyNames.add("dirtyNickel");
				itemDirtyNames.add("dirtyPlatinum");
				itemDirtyNames.add("dirtySilver");
				itemDirtyNames.add("dirtyTin");
				itemDirtyNames.add("dirtyZinc");
				registerItem(itemDirty = new ItemDirty(itemDirtyNames), "itemDirty");
				registerItem(itemJug_2 = new ItemWaterJug(2), "itemJug_2");
				registerItem(itemJug_4 = new ItemWaterJug(4), "itemJug_4");
				registerItem(itemJug_6 = new ItemWaterJug(6), "itemJug_6");
				registerItem(itemJug_12 = new ItemWaterJug(12), "itemJug_12");
				registerItem(itemJug_24 = new ItemWaterJug(24), "itemJug_24");
				registerItem(itemJug_48 = new ItemWaterJug(48), "itemJug_48");
				registerItem(creditBismuth = new ItemCredit("bismuthCredit"), "creditBismuth");
				registerItem(creditCopper = new ItemCredit("copperCredit"), "creditCopper");
				registerItem(creditGold = new ItemCredit("goldCredit"), "creditGold");
				registerItem(creditIron = new ItemCredit("ironCredit"), "creditIron");
				registerItem(creditLead = new ItemCredit("leadCredit"), "creditLead");
				registerItem(creditNickel = new ItemCredit("nickelCredit"), "creditNickel");
				registerItem(creditPlatinum = new ItemCredit("platinumCredit"), "creditPlatinum");
				registerItem(creditSilver = new ItemCredit("silverCredit"), "creditSilver");
				registerItem(creditTin = new ItemCredit("tinCredit"), "creditTin");
				registerItem(creditZinc = new ItemCredit("zincCredit"), "creditZinc");
				itemCastNames.add("doubleIngotCast");
				itemCastNames.add("sheetCast");
				itemCastNames.add("2xsheetCast");
				itemCastNames.add("javelinCast");
				itemCastNames.add("proPickCast");
				itemCastNames.add("pickCast");
				itemCastNames.add("scytheCast");
				itemCastNames.add("hammerCast");
				itemCastNames.add("axeCast");
				itemCastNames.add("shovelCast");
				itemCastNames.add("swordCast");
				itemCastNames.add("sawCast");
				itemCastNames.add("knifeCast");
				itemCastNames.add("tuyereCast");
				itemCastNames.add("hoeCast");
				itemCastNames.add("iceSawCast");
				itemCastNames.add("linkCast");
				itemCastNames.add("boltCast");
				itemCastNames.add("arrowHeadCast");
				itemCastNames.add("warHammerCast");
				itemCastNames.add("poniardCast");
				itemCastNames.add("chiselCast");
				itemCastNames.add("maceCast");
				itemCastNames.add("halberdCast");
				registerItem(itemCast = new ItemMaterial(itemCastNames, "itemCast"), "itemCast");
				itemMetalCastNames.add("metalEmpty");
				itemMetalCastNames.add("metalBismuth");
				itemMetalCastNames.add("metalBismuthBronze");
				itemMetalCastNames.add("metalBlackBronze");
				itemMetalCastNames.add("metalBlackSteel");
				itemMetalCastNames.add("metalBlueSteel");
				itemMetalCastNames.add("metalBrass");
				itemMetalCastNames.add("metalBronze");
				itemMetalCastNames.add("metalCopper");
				itemMetalCastNames.add("metalGold");
				itemMetalCastNames.add("metalIron");
				itemMetalCastNames.add("metalLead");
				itemMetalCastNames.add("metalNickel");
				itemMetalCastNames.add("metalPigIron");
				itemMetalCastNames.add("metalPlatinum");
				itemMetalCastNames.add("metalRedSteel");
				itemMetalCastNames.add("metalRoseGold");
				itemMetalCastNames.add("metalSilver");
				itemMetalCastNames.add("metalSteel");
				itemMetalCastNames.add("metalSterlingSilver");
				itemMetalCastNames.add("metalTin");
				itemMetalCastNames.add("metalZinc");
				registerItem(itemMetalCast = new ItemMaterial(itemMetalCastNames, "itemMetalCast"), "itemMetalCast");
				itemTokenNames.add("token");
				itemTokenColors.put("token", EnumChatFormatting.LIGHT_PURPLE);
				registerItem(itemToken = new ItemToken(itemTokenNames, itemTokenColors).setUnlocalizedName("token"), "token");
				registerItem(helmetDarkMatter = new ArmorDarkMatter(DARKMATTER, 0, 0).setUnlocalizedName("helmetDarkMatter"), "helmetDarkMatter");
				registerItem(chestDarkMatter = new ArmorDarkMatter(DARKMATTER, 0, 1).setUnlocalizedName("chestDarkMatter"), "chestDarkMatter");
				registerItem(leggsDarkMatter = new ArmorDarkMatter(DARKMATTER, 1, 2).setUnlocalizedName("leggingsDarkMatter"), "leggingsDarkMatter");
				registerItem(bootsDarkMatter = new ArmorDarkMatter(DARKMATTER, 0, 3).setUnlocalizedName("bootsDarkMatter"), "bootDarkMatter");
				registerItem(helmetRedMatter = new ArmorRedMatter(REDMATTER, 0, 0).setUnlocalizedName("helmetRedMatter"), "helmetRedMatter");
				registerItem(chestRedMatter = new ArmorRedMatter(REDMATTER, 0, 1).setUnlocalizedName("chestRedMatter"), "chestRedMatter");
				registerItem(leggsRedMatter = new ArmorRedMatter(REDMATTER, 1, 2).setUnlocalizedName("leggingsRedMatter"), "leggingsRedMatter");
				registerItem(bootsRedMatter = new ArmorRedMatter(REDMATTER, 0, 3).setUnlocalizedName("bootsRedMatter"), "bootsRedMatter");
		}

		private static void registerItem (Item item, String name) {
				GameRegistry.registerItem(item, name);
		}
}
