package wurmcraft.wurmatron.common.recipes.mods;

import WayofTime.alchemicalWizardry.ModItems;
import am2.items.ItemsCommonProxy;
import cofh.thermalfoundation.item.TFItems;
import com.bioxx.tfc.api.TFCItems;
import com.lulan.shincolle.init.ModBlocks;
import com.rwtema.extrautils.ExtraUtils;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.common.config.ConfigBlocks;
import thaumcraft.common.config.ConfigItems;
import wurmcraft.wurmatron.common.items.WurmTweaksItems;
import wurmcraft.wurmatron.common.recipes.RecipeHelper;
import wurmcraft.wurmatron.common.utils.nbt.ItemNBT;
import wurmcraft.wurmatron.common.utils.thaumcraft.ThaumcraftHelper;

public class ThamicTinkersRecipes {

		private static final RecipeHelper r = new RecipeHelper();

		public static void addRecipes () {
				ThaumcraftHelper.removeResearch("ANIMATION_TABLET");
				ThaumcraftHelper.removeResearch("LEVITATOR");
				ThaumcraftHelper.removeResearch("FIRE_TERRA");
				ThaumcraftHelper.removeResearch("GOLEM_CONNECTOR");
				ThaumcraftHelper.removeResearch("SUMMON");
				ThaumcraftHelper.removeResearch("FOCUS_RECALL");
				ThaumcraftHelper.removeResearch("MAGNETS");
				ThaumcraftHelper.removeResearch("FIRE_AER");
				ThaumcraftHelper.removeResearch("FIRE_PERDITIO");
				ThaumcraftHelper.removeResearch("SHARE_TOME");
				ThaumcraftHelper.removeResearch("FIRE_IGNIS");
				ThaumcraftHelper.removeResearch("FIRE_ORDO");
				ThaumcraftHelper.removeResearch("FIRE_AQUA");
				ThaumcraftHelper.removeResearch("INFUSED_POTIONS");
				ThaumcraftHelper.removeResearch("REPAIRER");
				ThaumcraftHelper.addShaped("INTERFACE", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "interface")), new AspectList().add(Aspect.ENTROPY, 25).add(Aspect.ORDER, 25), "XAX", "ACA", "XAX", 'X', new ItemStack(ConfigBlocks.blockCosmeticSolid, 1, 6), 'A', Items.redstone, 'C', Items.ender_pearl);
				ThaumcraftHelper.addShaped("INTERFACE", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "connector")), new AspectList().add(Aspect.ORDER, 2), " I ", " SI", "S  ", 'I', "packIngot", 'S', "packStick");
				r.addShaped(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "darkQuartzItem"), 4), "X X", " C ", "X X", 'X', Items.quartz, 'C', new ItemStack(TFCItems.coal, 1, 1));
				r.addShaped(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "darkQuartzItem"), 8), "X X", " C ", "X X", 'X', Items.quartz, 'C', new ItemStack(TFCItems.coal, 1, 0));
				ThaumcraftHelper.refreshResearch("DARK_QUARTZ");
				ThaumcraftHelper.addInfusion("BLOCK_TALISMAN", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "cleansingTailsman"), 1), 10, new AspectList().add(Aspect.HUNGER, 12).add(Aspect.ARMOR, 24).add(Aspect.DEATH, 12), new ItemStack(Items.ender_pearl), new ItemStack[] {new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "darkQuartzItem"), 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "darkQuartzItem"), 1), new ItemStack(TFCItems.blueSteelChestplate), WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemCraftingCore});
				ThaumcraftHelper.addInfusion("BLOOD_SWORD", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "bloodSword"), 1), 3650), 16, new AspectList().add(Aspect.DARKNESS, 32).add(Aspect.DEATH, 32).add(Aspect.HUNGER, 16), new ItemStack(TFCItems.blueSteelSword), new ItemStack[] {new ItemStack(Items.ghast_tear), new ItemStack(ModBlocks.BlockGrudgeHeavy), WurmTweaksItems.ingotCyanSteel});
				ThaumcraftHelper.addInfusion("BLOOD_SWORD", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "bloodSword"), 1), 3650), 16, new AspectList().add(Aspect.DARKNESS, 32).add(Aspect.DEATH, 32).add(Aspect.HUNGER, 16), new ItemStack(TFCItems.redSteelSword), new ItemStack[] {new ItemStack(Items.ghast_tear), new ItemStack(ModBlocks.BlockGrudgeHeavy), WurmTweaksItems.ingotCyanSteel});
				ThaumcraftHelper.addShaped("PLATFORM", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "platform"), 2), new AspectList().add(Aspect.AIR, 4).add(Aspect.ENTROPY, 4), "PSP", 'P', new ItemStack(ConfigBlocks.blockMagicalLog, 1, 0), 'S', new ItemStack(ConfigBlocks.blockMagicalLog, 1, 1));
				ThaumcraftHelper.refreshResearch("TTENCH_AUTO_SMELT");
				ThaumcraftHelper.refreshResearch("FOCUS_SMELT");
				ThaumcraftHelper.addInfusion("PROTOCLAY", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "protoclay")), 12, new AspectList().add(Aspect.AIR, 32).add(Aspect.MAGIC, 32).add(Aspect.TOOL, 64), new ItemStack(TFCItems.clayBall), new ItemStack[] {new ItemStack(Blocks.stone), new ItemStack(ExtraUtils.bedrockiumBlock), WurmTweaksItems.ingotCyanSteel});
				ThaumcraftHelper.addInfusion("ICHOR", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 2), 4, new AspectList().add(Aspect.HUNGER, 32).add(Aspect.MAGIC, 64).add(Aspect.BEAST, 32), new ItemStack(Items.nether_star), new ItemStack[] {new ItemStack(ExtraUtils.bedrockium), WurmTweaksItems.ingotRainbowSteel, WurmTweaksItems.itemBloodInfused, WurmTweaksItems.itemCraftingCore});
				ThaumcraftHelper.removeResearch("FUNNEL");
				ThaumcraftHelper.addCrucible("BRIGHT_NITOR", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "brightNitor")), new ItemStack(ConfigItems.itemResource, 1, 1), new AspectList().add(Aspect.LIGHT, 16).add(Aspect.FIRE, 32).add(Aspect.ENERGY, 8));
				ThaumcraftHelper.addInfusion("ICHORCLOTH_CHEST_GEM", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothChestGem")), 0, new AspectList().add(Aspect.MAGIC, 256).add(Aspect.AIR, 256).add(Aspect.ARMOR, 128).add(Aspect.ELDRITCH, 64), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothChest")), new ItemStack[] {WurmTweaksItems.itemNatureCoreMK2, WurmTweaksItems.ingotTitanium, WurmTweaksItems.itemCraftingCore, WurmTweaksItems.ingotRainbowSteel, new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(ItemsCommonProxy.battlemageArmor), new ItemStack(ModItems.weakBloodShard), new ItemStack(techreborn.init.ModBlocks.FusionCoil), TFItems.ingotEnderium, new ItemStack(com.brandon3055.draconicevolution.common.ModItems.draconicIngot, 1, 0)});
				ThaumcraftHelper.removeResearch("REVEALING_HELM");
				ThaumcraftHelper.addInfusion("FOCUS_XP_DRAIN", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "focusXPDrain")), 20, new AspectList().add(Aspect.AIR, 32).add(Aspect.MAGIC, 32).add(Aspect.DARKNESS, 32), new ItemStack(ConfigItems.itemFocusShock), new ItemStack[] {new ItemStack(Blocks.enchanting_table), new ItemStack(ConfigItems.itemFocusExcavation), new ItemStack(TFCItems.arrow), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"))});
				ThaumcraftHelper.addInfusion("ROD_ICHORCLOTH", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 5), 8, new AspectList().add(Aspect.TOOL, 64).add(Aspect.MAGIC, 32).add(Aspect.AIR, 32), new ItemStack(ConfigItems.itemWandRod, 1, 2), new ItemStack[] {new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemCraftingCore});
				ThaumcraftHelper.addShaped("ICHORIUM", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 2), new AspectList().add(Aspect.AIR, 100).add(Aspect.FIRE, 100).add(Aspect.WATER, 100).add(Aspect.ENTROPY, 100).add(Aspect.EARTH, 100), " I ", "CXC", " C ", 'I', "packIngot", 'C', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), 'X', "packGemExquisite");
				ThaumcraftHelper.addCrucible("GASEOUS_LIGHT", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "gaseousLightItem")), new ItemStack(Items.glowstone_dust), new AspectList().add(Aspect.AIR, 16).add(Aspect.LIGHT, 8).add(Aspect.MOTION, 8));
				ThaumcraftHelper.removeResearch("CAT_AMULET");
				ThaumcraftHelper.addInfusion("ICHOR_SHOVEL_GEM", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorShovelGem")), 1500), 8, new AspectList().add(Aspect.FIRE, 32).add(Aspect.MOTION, 32).add(Aspect.TOOL, 128), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorShovel")), new ItemStack[] {new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(TFCItems.blueSteelShovel), new ItemStack(TFCItems.redSteelShovel), new ItemStack(ConfigItems.itemFocusExcavation), new ItemStack(Blocks.tnt), WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemNatureCore});
				ThaumcraftHelper.addShaped("ICHOR_CLOTH", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new AspectList().add(Aspect.AIR, 125).add(Aspect.WATER, 125).add(Aspect.EARTH, 125).add(Aspect.FIRE, 125).add(Aspect.ORDER, 125).add(Aspect.ENTROPY, 125), "SSS", "XXX", "AAA", 'S', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 0), 'X', new ItemStack(ConfigItems.itemResource, 1, 7), 'A', "packGemExquisite");
				ThaumcraftHelper.addShaped("ICHORCLOTH_ARMOR", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothHelm")), new AspectList().add(Aspect.WATER, 75), "SSS", "S S", 'S', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1));
				ThaumcraftHelper.addShaped("ICHORCLOTH_ARMOR", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothChest")), new AspectList().add(Aspect.EARTH, 75), "S S", "SSS", "SSS", 'S', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1));
				ThaumcraftHelper.addShaped("ICHORCLOTH_ARMOR", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothLegs")), new AspectList().add(Aspect.FIRE, 75), "SSS", "S S", "S S", 'S', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1));
				ThaumcraftHelper.addShaped("ICHORCLOTH_ARMOR", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothBoots")), new AspectList().add(Aspect.ORDER, 75), "S S", "S S", 'S', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1));
				ThaumcraftHelper.addShaped("CAP_ICHOR", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 2, 4), new AspectList().add(Aspect.AIR, 100).add(Aspect.FIRE, 100).add(Aspect.WATER, 100).add(Aspect.ENTROPY, 100).add(Aspect.EARTH, 100), "ICI", " X ", "ICI", 'I', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 0), 'C', new ItemStack(ConfigItems.itemWandCap, 1, 2), 'X', WurmTweaksItems.ingotRainbowSteel);
				ThaumcraftHelper.addInfusion("ENCHANTER", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "enchanter")), 12, new AspectList().add(Aspect.MAGIC, 256).add(Aspect.TAINT, 24).add(Aspect.DARKNESS, 32), new ItemStack(Blocks.enchanting_table), new ItemStack[] {new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "spellCloth")), WurmTweaksItems.itemNatureCoreMK2, WurmTweaksItems.itemCraftingCore, WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemCraftingCore, WurmTweaksItems.ingotEnergyReactor});
				ThaumcraftHelper.addInfusion("ICHORCLOTH_LEGS_GEM", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothLegsGem")), 0, new AspectList().add(Aspect.MAGIC, 256).add(Aspect.AIR, 256).add(Aspect.ARMOR, 128).add(Aspect.ELDRITCH, 64), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothLegs")), new ItemStack[] {WurmTweaksItems.itemNatureCoreMK2, WurmTweaksItems.ingotTitanium, WurmTweaksItems.itemCraftingCore, WurmTweaksItems.ingotRainbowSteel, new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(ItemsCommonProxy.battlemageLeggings), new ItemStack(ModItems.weakBloodShard), new ItemStack(techreborn.init.ModBlocks.FusionCoil), TFItems.ingotEnderium, new ItemStack(com.brandon3055.draconicevolution.common.ModItems.draconicIngot, 1, 0)});
				ThaumcraftHelper.addInfusion("ICHORCLOTH_BOOTS_GEM", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothBootsGem")), 0, new AspectList().add(Aspect.MAGIC, 256).add(Aspect.AIR, 256).add(Aspect.ARMOR, 128).add(Aspect.ELDRITCH, 64), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorclothBoots")), new ItemStack[] {WurmTweaksItems.itemNatureCoreMK2, WurmTweaksItems.ingotTitanium, WurmTweaksItems.itemCraftingCore, WurmTweaksItems.ingotRainbowSteel, new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(ItemsCommonProxy.battlemageBoots), new ItemStack(ModItems.weakBloodShard), new ItemStack(techreborn.init.ModBlocks.FusionCoil), TFItems.ingotEnderium, new ItemStack(com.brandon3055.draconicevolution.common.ModItems.draconicIngot, 1, 0)});
				ThaumcraftHelper.addInfusion("ICHOR_AXE_GEM", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorAxeGem")), 1850), 8, new AspectList().add(Aspect.FIRE, 32).add(Aspect.MOTION, 32).add(Aspect.TOOL, 128), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorAxe")), new ItemStack[] {new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(TFCItems.blueSteelAxe), new ItemStack(TFCItems.redSteelAxe), new ItemStack(ConfigItems.itemFocusExcavation), new ItemStack(Blocks.tnt), WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemNatureCore});
				ThaumcraftHelper.addInfusion("ICHOR_PICK_GEM", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorPickGem")), 2000), 8, new AspectList().add(Aspect.FIRE, 32).add(Aspect.MOTION, 32).add(Aspect.TOOL, 128), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorAxe")), new ItemStack[] {new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(TFCItems.blueSteelPick), new ItemStack(TFCItems.redSteelPick), new ItemStack(ConfigItems.itemFocusExcavation), new ItemStack(Blocks.tnt), WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemNatureCore});
				ThaumcraftHelper.addInfusion("ICHOR_SWORD_GEM", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorSwordGem")), 3000), 8, new AspectList().add(Aspect.FIRE, 32).add(Aspect.MOTION, 32).add(Aspect.TOOL, 128), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorSword")), new ItemStack[] {new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 1), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(TFCItems.blueSteelPick), new ItemStack(TFCItems.redSteelPick), new ItemStack(ConfigItems.itemFocusExcavation), new ItemStack(Blocks.tnt), WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemNatureCore});
				ThaumcraftHelper.addCrucible("GASEOUS_SHADOW", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "gaseousShadowItem")), new ItemStack(Items.ender_pearl), new AspectList().add(Aspect.AIR, 16).add(Aspect.LIGHT, 8).add(Aspect.MOTION, 8));
				ThaumcraftHelper.addCrucible("SPELL_CLOTH", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "spellCloth")), new ItemStack(ConfigItems.itemResource, 1, 7), new AspectList().add(Aspect.DARKNESS, 8).add(Aspect.TREE, 8).add(Aspect.MAGIC, 16));
				ThaumcraftHelper.addShaped("ICHOR_TOOLS", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorPick")), 580), new AspectList().add(Aspect.FIRE, 75), "III", " S ", " S ", 'I', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 2), 'S', new ItemStack(ConfigItems.itemWandRod, 1, 2));
				ThaumcraftHelper.addShaped("ICHOR_TOOLS", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorAxe")), 650), new AspectList().add(Aspect.WATER, 75), "II ", "IS ", " S ", 'I', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 2), 'S', new ItemStack(ConfigItems.itemWandRod, 1, 2));
				ThaumcraftHelper.addShaped("ICHOR_TOOLS", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorAxe")), 650), new AspectList().add(Aspect.WATER, 75), " II", " SI", " S ", 'I', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 2), 'S', new ItemStack(ConfigItems.itemWandRod, 1, 2));
				ThaumcraftHelper.addShaped("ICHOR_TOOLS", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorShovel")), 520), new AspectList().add(Aspect.ORDER, 75), " I ", " S ", " S ", 'I', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 2), 'S', new ItemStack(ConfigItems.itemWandRod, 1, 2));
				ThaumcraftHelper.addShaped("ICHOR_TOOLS", ItemNBT.addDamage(new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "ichorSword")), 1200), new AspectList().add(Aspect.ORDER, 75), " I ", " I ", " S ", 'I', new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"), 1, 2), 'S', new ItemStack(ConfigItems.itemWandRod, 1, 2));
				ThaumcraftHelper.addInfusion("FOCUS_SHADOWBEAM", new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "focusShadowbeam")), 24, new AspectList().add(Aspect.AIR, 32).add(Aspect.MAGIC, 32).add(Aspect.DARKNESS, 32), new ItemStack(ConfigItems.itemFocusShock), new ItemStack[] {new ItemStack(Blocks.tnt), new ItemStack(ConfigItems.itemFocusFire), new ItemStack(TFCItems.arrow), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource")), new ItemStack(GameRegistry.findItem("ThaumicTinkerer", "kamiResource"))});
				ThaumcraftHelper.removeResearch("WARP_GATE");
		}
}
