package wurmcraft.wurmatron.common.recipes.mods;

import cofh.core.util.crafting.RecipeAugmentable;
import cofh.core.util.crafting.RecipeUpgrade;
import cofh.thermalexpansion.block.TEBlocks;
import cofh.thermalexpansion.block.cache.BlockCache;
import cofh.thermalexpansion.block.cell.BlockCell;
import cofh.thermalexpansion.block.device.BlockDevice;
import cofh.thermalexpansion.block.dynamo.BlockDynamo;
import cofh.thermalexpansion.block.ender.BlockEnder;
import cofh.thermalexpansion.block.simple.BlockFrame;
import cofh.thermalexpansion.block.simple.BlockRockwool;
import cofh.thermalexpansion.block.sponge.BlockSponge;
import cofh.thermalexpansion.block.strongbox.BlockStrongbox;
import cofh.thermalexpansion.block.tank.BlockTank;
import cofh.thermalexpansion.block.workbench.BlockWorkbench;
import cofh.thermalexpansion.item.TEAugments;
import cofh.thermalexpansion.item.TEItems;
import cofh.thermalexpansion.util.crafting.TECraftingHandler;
import cofh.thermalfoundation.item.TFItems;
import com.bioxx.tfc.api.TFCItems;
import cpw.mods.fml.common.Optional;
import cpw.mods.fml.common.registry.GameRegistry;
import crazypants.enderio.EnderIO;
import fox.spiteful.avaritia.items.LudicrousItems;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;
import wurmcraft.wurmatron.common.items.WurmTweaksItems;
import wurmcraft.wurmatron.common.recipes.RecipeHelper;
import wurmcraft.wurmatron.common.utils.buildcraft.BuildCraftHelper;
import wurmcraft.wurmatron.common.utils.nbt.ItemNBT;
import wurmcraft.wurmatron.common.utils.tfc.TFCHelper;
import wurmcraft.wurmatron.common.utils.thermalexpansion.TEHelper;

public class ThermalExpansionRecipes {


		private static RecipeHelper r = new RecipeHelper();

		@Optional.Method (modid = "ThermalExpansion")
		public static void addRecipes () {
				BuildCraftHelper.addAssemblerRecipes("te:basicmachineframe", 12000, BlockFrame.frameCellBasic, WurmTweaksItems.itemMachineFrame, new ItemStack(EnderIO.itemBasicCapacitor, 4, 0), new ItemStack(TFCItems.blackSteelSheet, 4));
				BuildCraftHelper.addAssemblerRecipes("te:hardmachineframe", 240000, BlockFrame.frameCellHardened, new ItemStack(WurmTweaksItems.itemMachineFrame.getItem(), 2, 33), new ItemStack(EnderIO.itemBasicCapacitor, 4, 1), new ItemStack(TFCItems.redSteelSheet, 4));
				BuildCraftHelper.addAssemblerRecipes("te:reinforcedmachineframe", 1200000, BlockFrame.frameMachineReinforced, new ItemStack(WurmTweaksItems.itemMachineFrame.getItem(), 3, 33), new ItemStack(EnderIO.itemBasicCapacitor, 4, 2), new ItemStack(TFCItems.platinumSheet2x, 4));
				BuildCraftHelper.addAssemblerRecipes("te:enderiummachineframe", 12000000, BlockFrame.frameMachineResonant, new ItemStack(WurmTweaksItems.itemMachineFrame.getItem(), 4, 33), new ItemStack(EnderIO.itemBasicCapacitor, 4, 2), new ItemStack(TFCItems.platinumSheet2x, 4), TFItems.ingotEnderium);
				r.addShaped(ItemNBT.addDamage(new ItemStack(TEItems.itemBattleWrench), 280), "III", " I ", " I ", 'I', new ItemStack(TFCItems.steelSheet));
				r.addShaped(new ItemStack(TEItems.itemMaterial, 1, 16), " I ", "ICI", "III", 'I', new ItemStack(TFItems.itemMaterial, 1, 74), 'C', TFCItems.bronzeIngot);
				r.addShaped(TEHelper.getMagma("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getMagma("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getMagma("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getMagma("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getFluid("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getCobble("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getFluid("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAqua("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getAqua("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAqua("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAqua("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAssembler("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getAssembler("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAssembler("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAssembler("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPower("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getPower("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPower("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPower("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(ItemNBT.addDamage(TEItems.toolWrench, 120), "I I", " T ", " I ", 'I', new ItemStack(TFCItems.wroughtIronIngot), 'T', new ItemStack(TFCItems.tinIngot));
				r.addShaped(TEItems.toolMultimeter, "C C", "LPL", " G ", 'C', new ItemStack(TFCItems.copperIngot), 'L', new ItemStack(TFCItems.leadIngot), 'P', cofh.thermalexpansion.item.TEItems.powerCoilElectrum, 'G', new ItemStack(TFCItems.roseGoldSheet2x));
				r.addShaped(TEItems.capacitorPotato, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.leadIngot), 'R', new ItemStack(Items.redstone), 'X', TFCHelper.getFood(TFCItems.potato, 160), 'Y', "dustSulfur");
				r.addShaped(TEItems.capacitorBasic, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.leadIngot), 'R', new ItemStack(Items.redstone), 'X', new ItemStack(TFCItems.blackSteelIngot), 'Y', "dustSulfur");
				r.addShaped(TEItems.capacitorHardened, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.nickelIngot), 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorBasic, 'Y', new ItemStack(TFCItems.blueSteelIngot));
				r.addShaped(TEItems.capacitorHardened, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.nickelIngot), 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorBasic, 'Y', new ItemStack(TFCItems.blueSteelIngot));
				r.addShaped(TEItems.capacitorReinforced, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.roseGoldSheet), 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorHardened, 'Y', "packGemExquisite");
				r.addShaped(TEItems.capacitorResonant, " R ", "IXI", "RYR", 'I', TFItems.ingotEnderium, 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorReinforced, 'Y', TFItems.dustPyrotheum);
				r.addShaped(cofh.thermalexpansion.item.TEItems.satchelBasic, " Y ", "IXI", "Y Y", 'I', new ItemStack(TFCItems.bismuthSheet), 'X', new ItemStack(TFCItems.silkCloth), 'Y', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE));
				r.addShaped(TEItems.satchelHardened, " Y ", "IXI", "Y Y", 'I', new ItemStack(TFCItems.nickelIngot), 'X', cofh.thermalexpansion.item.TEItems.satchelBasic, 'Y', new ItemStack(TFCItems.zincIngot));
				r.addShaped(TEItems.satchelReinforced, " Y ", "IXI", "Y Y", 'I', "packGlass", 'X', cofh.thermalexpansion.item.TEItems.satchelHardened, 'Y', new ItemStack(TFCItems.roseGoldIngot));
				r.addShaped(TEItems.satchelResonant, " Y ", "IXI", "Y Y", 'I', new ItemStack(TFCItems.steelIngot), 'X', cofh.thermalexpansion.item.TEItems.satchelReinforced, 'Y', TFItems.ingotEnderium);
				TECraftingHandler.addSecureRecipe(TEItems.satchelCreative);
				TECraftingHandler.addSecureRecipe(TEItems.satchelBasic);
				TECraftingHandler.addSecureRecipe(TEItems.satchelHardened);
				TECraftingHandler.addSecureRecipe(TEItems.satchelReinforced);
				TECraftingHandler.addSecureRecipe(TEItems.satchelResonant);
				r.addShaped(TEItems.pneumaticServo, " I ", "GRG", " I ", 'R', new ItemStack(Items.redstone), 'G', "packGlass", 'I', new ItemStack(TFCItems.steelIngot));
				r.addShaped(TEItems.powerCoilGold, "  R", " G ", "R  ", 'R', new ItemStack(Items.redstone), 'G', new ItemStack(TFCItems.goldIngot));
				r.addShaped(TEItems.powerCoilSilver, "  R", " G ", "R  ", 'R', new ItemStack(Items.redstone), 'G', new ItemStack(TFCItems.silverIngot));
				r.addShaped(TEItems.powerCoilElectrum, "R  ", " G ", "  R", 'R', new ItemStack(Items.redstone), 'G', new ItemStack(TFCItems.roseGoldIngot));
				r.addShaped(TEAugments.generalAutoInput, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinIngot), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo);
				r.addShaped(TEAugments.generalAutoOutput, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinSheet), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo);
				r.addShaped(TEAugments.generalReconfigSides, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinSheet), 'X', new ItemStack(TFCItems.goldSheet));
				r.addShaped(TEAugments.generalRedstoneControl, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinSheet), 'X', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.dynamoCoilDuct, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.leadSheet), 'X', new ItemStack(TFCItems.copperIngot));
				r.addShaped(TEAugments.dynamoEfficiency[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.leadSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', new ItemStack(TFCItems.tinIngot), 'Y', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.dynamoEfficiency[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.leadSheet), 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', Items.glowstone_dust);
				r.addShaped(TEAugments.dynamoEfficiency[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', TFItems.dustCryotheum);
				r.addShaped(TEAugments.dynamoOutput[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.copperIngot), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.dynamoOutput[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.copperIngot), 'I', new ItemStack(TFCItems.silverSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', Items.glowstone_dust);
				r.addShaped(TEAugments.dynamoOutput[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.silverSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', TFItems.dustCryotheum);
				r.addShaped(TEAugments.machineSecondary[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.brassIngot), 'X', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE), 'Y', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE));
				r.addShaped(TEAugments.machineSecondary[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.brassIngot), 'I', "packGlass", 'X', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE), 'Y', Items.glowstone_dust);
				r.addShaped(TEAugments.machineSecondary[2], " I ", "IXI", "YIY", 'I', "packGlass", 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', TFItems.dustCryotheum);
				r.addShaped(TEAugments.machineSpeed[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.brassIngot), 'X', cofh.thermalexpansion.item.TEItems.powerCoilGold, 'Y', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.machineSpeed[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.brassIngot), 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilGold, 'Y', TFItems.dustPyrotheum);
				r.addShaped(TEAugments.machineSpeed[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilGold, 'Y', new ItemStack(Items.nether_star));
				r.addShaped(TEAugments.machineExtruderBoost[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.brassIngot), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', "packGemExquisite");
				r.addShaped(TEAugments.machineExtruderBoost[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.brassIngot), 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', Blocks.redstone_block);
				r.addShaped(TEAugments.machineExtruderBoost[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', "packGemExquisite");
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoSteam, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.copperSheet2x), 'I', new ItemStack(TFCItems.copperIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoMagmatic, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.nickelSheet2x), 'I', new ItemStack(TFCItems.nickelIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoCompression, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.steelSheet2x), 'I', new ItemStack(TFCItems.steelIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoReactant, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.blackSteelSheet2x), 'I', new ItemStack(TFCItems.blackSteelIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoEnervation, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.redSteelSheet2x), 'I', new ItemStack(TFCItems.redSteelIngot), 'R', new ItemStack(Items.redstone)}));
				r.addShaped(BlockCache.cacheHardened, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', BlockCache.cacheBasic);
				r.addShaped(BlockCache.cacheReinforced, " G ", "GXG", " G ", 'X', BlockCache.cacheHardened, 'G', "packGlass");
				r.addShaped(BlockCache.cacheResonant, " I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockCache.cacheReinforced);
				r.addShaped(BlockStrongbox.strongboxReinforced, " G ", "GXG", " G ", 'X', BlockStrongbox.strongboxHardened, 'G', "packGlass");
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDevice.breaker, BlockDevice.defaultAugments, new Object[] {" X ", "ICI", " P ", 'C', new ItemStack(TFCItems.copperIngot), 'I', new ItemStack(TFCItems.roseGoldIngot), 'P', TEItems.pneumaticServo, 'X', new ItemStack(TFCItems.redSteelPick)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDevice.nullifier, BlockDevice.defaultAugments, new Object[] {" X ", "ICI", " P ", 'C', "packChest", 'I', new ItemStack(TFCItems.blueSteelBucketLava), 'P', TEItems.pneumaticServo, 'X', new ItemStack(TFCItems.nickelIngot)}));
				GameRegistry.addRecipe(new RecipeUpgrade(BlockStrongbox.strongboxResonant, new Object[] {" I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockStrongbox.strongboxReinforced}));
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoSteam);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoMagmatic);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoCompression);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoEnervation);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoReactant);
				r.addShaped(BlockCache.cacheBasic, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinIngot), 'X', "packLog");
				r.addShaped(BlockCache.cacheHardened, "IYI", "YXY", "IYI", 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', "packLog", 'Y', new ItemStack(TFCItems.tinIngot));
				r.addShaped(BlockTank.tankBasic, " G ", "GXG", " G ", 'G', "packGlass", 'X', new ItemStack(TFCItems.copperIngot));
				r.addShaped(BlockStrongbox.strongboxHardened, "IYI", "YXY", "IYI", 'I', new ItemStack(TFCItems.brassIngot), 'X', "packChest", 'Y', new ItemStack(TFCItems.steelIngot));
				GameRegistry.addRecipe(new RecipeUpgrade(BlockStrongbox.strongboxResonant, new Object[] {" I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockStrongbox.strongboxReinforced}));
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxCreative);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxBasic);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxHardened);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxReinforced);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxResonant);
				r.addShaped(BlockEnder.tesseract, "BIB", "ICI", "BIB", 'C', BlockFrame.frameTesseractFull, 'I', new ItemStack(TFCItems.redSteelSheet2x), 'B', new ItemStack(TFCItems.blueSteelSheet2x));
				TECraftingHandler.addSecureRecipe(BlockEnder.tesseract);
				TECraftingHandler.addSecureRecipe(BlockCell.cellCreative);
				TECraftingHandler.addSecureRecipe(BlockCell.cellBasic);
				TECraftingHandler.addSecureRecipe(BlockCell.cellHardened);
				TECraftingHandler.addSecureRecipe(BlockCell.cellReinforced);
				TECraftingHandler.addSecureRecipe(BlockCell.cellResonant);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchBasic);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchHardened);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchReinforced);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchResonant);
				TECraftingHandler.addSecureRecipe(BlockDevice.activator);
				TECraftingHandler.addSecureRecipe(BlockDevice.breaker);
				TECraftingHandler.addSecureRecipe(BlockDevice.nullifier);
				r.addShaped(BlockDevice.activator, "SPS", "ECE", "SXS", 'S', WurmTweaksItems.itemMixedSheet, 'P', new ItemStack(TFCItems.blueSteelPick), 'X', new ItemStack(TFCItems.redSteelShovel), 'E', "packGemExquisite", 'C', "packChest");
				r.addShaped(BlockCell.cellBasic, " I ", "IXI", " P ", 'I', new ItemStack(TFCItems.steelIngot), 'X', BlockFrame.frameCellBasic, 'P', TEItems.powerCoilElectrum);
				r.addShaped(BlockCell.cellHardened, " I ", "IXI", " P ", 'I', new ItemStack(TFCItems.steelIngot), 'X', BlockFrame.frameCellHardened, 'P', TEItems.powerCoilElectrum);
				r.addShaped(BlockCell.cellReinforced, " X ", "YCY", "IPI", 'C', BlockFrame.frameCellReinforcedFull, 'I', new ItemStack(TFCItems.leadIngot), 'P', TEItems.powerCoilElectrum, 'X', TFItems.ingotEnderium, 'Y', TFItems.ingotEnderium);
				r.addShaped(BlockCell.cellResonant, " X ", "YCY", "IPI", 'C', BlockFrame.frameCellResonantFull, 'I', new ItemStack(TFCItems.leadIngot), 'P', TEItems.powerCoilElectrum, 'X', TFItems.ingotEnderium, 'Y', TFItems.ingotEnderium);
				r.addShaped(BlockFrame.frameCellBasic, "IGI", "GXG", "IGI", 'I', new ItemStack(TFCItems.platinumIngot), 'G', "packGlass", 'X', Blocks.redstone_block);
				r.addShaped(BlockFrame.frameCellHardened, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.roseGoldIngot), 'X', BlockFrame.frameCellBasic);
				r.addShaped(BlockFrame.frameCellReinforcedEmpty, "IGI", "GXG", "IGI", 'I', TFItems.ingotEnderium, 'G', "packGlass", 'X', "packGemExquisite");
				r.addShaped(BlockFrame.frameCellResonantEmpty, " I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockFrame.frameCellReinforcedEmpty);
				r.addShaped(BlockFrame.frameCellResonantFull, " I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockFrame.frameCellReinforcedFull);
				r.addShaped(BlockFrame.frameTesseractEmpty, "IGI", "GXG", "IGI", 'I', TFItems.ingotEnderium, 'G', "packGlass", 'X', "packGemExquisite");
				r.addShaped(BlockSponge.spongeBasic, "SWS", "WBW", "SWS", 'S', Items.string, 'W', "packLog", 'B', Items.slime_ball);
				r.addShaped(BlockSponge.spongeMagmatic, "SWS", "WBW", "SWS", 'S', Items.string, 'W', "packLog", 'B', Items.magma_cream);
				r.addShaped(BlockWorkbench.workbenchBasic, " X ", "ICI", " P ", 'C', Blocks.crafting_table, 'I', "ingotCopper", 'P', BlockStrongbox.strongboxBasic, 'X', Items.paper);
				for (int d = 0; d < 15; d++)
						r.addCircleWCenter(new ItemStack(BlockRockwool.rockWool.getItem(), 8, d), "blockClothRock", RecipeHelper.dye.get(d));
				r.addShaped(TEHelper.getFurnace("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFurnace("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFurnace("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFurnace("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(new ItemStack(TFItems.itemMaterial, 4, 512), "BGB", "RRR", "BGB", 'B', Items.blaze_powder, 'G', Items.gunpowder, 'R', Items.redstone);
				r.addShaped(new ItemStack(TFItems.itemMaterial, 4, 513), "BGB", "RRR", "BGB", 'B', new ItemStack(TFItems.itemMaterial, 1, 1025), 'G', "dustSulfur", 'R', Items.redstone);
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 4, 44), new ItemStack(TFItems.itemBucket, 1, 2), TFCItems.platinumSheet, TFCItems.redSteelSheet, WurmTweaksItems.gearMixedSheet);
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 4, 42), new ItemStack(TFItems.itemBucket, 1, 0), TFCItems.platinumSheet, TFCItems.redSteelSheet, WurmTweaksItems.gearMixedSheet);
				r.addShapeless(new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 4, 44), TFCItems.tinSheet, TFCItems.platinumSheet, TFCItems.tinSheet, TFCItems.wroughtIronSheet, TFItems.bucketEnder);
				r.addShapeless(new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 4, 42), TFCItems.tinSheet, TFCItems.platinumSheet, TFCItems.tinSheet, TFCItems.wroughtIronSheet, TFItems.bucketRedstone);
				r.addShapeless(new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 9, 106), new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 1, 74));
				r.addShapeless(TEItems.diagramSchematic, Items.paper, Items.paper, "dyeBlue");
				r.addShapeless(TEItems.diagramRedprint, Items.paper, Items.paper, Items.redstone);
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 1, 74), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106));
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 9, 106), new ItemStack(TFItems.itemMaterial, 1, 74));
				r.addShaped9X9Recipe(new ItemStack(TEBlocks.blockCell, 1, 1), "CIIIIIIIC", "IBBBBBBBI", "IBXXXXXBI", "IBXXXXXBI", "IBXXXXXBI", "IBXXXXXBI", "IBXXXXXBI", "IBBBBBBBI", "CIIIIIIIC", 'C', WurmTweaksItems.creativeCreativePartsEnergy, 'I', new ItemStack(LudicrousItems.resource, 1, 5), 'B', new ItemStack(TEBlocks.blockCell, 1, 4), 'X', WurmTweaksItems.ingotRainbowSteel);
				r.addBasicMachineRecipe(TEItems.capacitorCreative, new ItemStack(LudicrousItems.resource, 1, 5), TEItems.capacitorResonant, WurmTweaksItems.creativeCreativeParts, new ItemStack(TEBlocks.blockCell, 1, 1));
		}
}
