package wurmcraft.wurmatron.common.recipes.mods;

import cofh.core.util.crafting.RecipeAugmentable;
import cofh.core.util.crafting.RecipeUpgrade;
import cofh.thermalexpansion.block.TEBlocks;
import cofh.thermalexpansion.block.cache.BlockCache;
import cofh.thermalexpansion.block.cell.BlockCell;
import cofh.thermalexpansion.block.device.BlockDevice;
import cofh.thermalexpansion.block.dynamo.BlockDynamo;
import cofh.thermalexpansion.block.ender.BlockEnder;
import cofh.thermalexpansion.block.simple.BlockFrame;
import cofh.thermalexpansion.block.simple.BlockRockwool;
import cofh.thermalexpansion.block.sponge.BlockSponge;
import cofh.thermalexpansion.block.strongbox.BlockStrongbox;
import cofh.thermalexpansion.block.tank.BlockTank;
import cofh.thermalexpansion.block.workbench.BlockWorkbench;
import cofh.thermalexpansion.item.TEAugments;
import cofh.thermalexpansion.item.TEItems;
import cofh.thermalexpansion.util.crafting.TECraftingHandler;
import cofh.thermalfoundation.item.TFItems;
import com.bioxx.tfc.api.TFCItems;
import cpw.mods.fml.common.Optional;
import cpw.mods.fml.common.registry.GameRegistry;
import crazypants.enderio.EnderIO;
import fox.spiteful.avaritia.items.LudicrousItems;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.oredict.OreDictionary;
import wurmcraft.wurmatron.common.blocks.WurmTweaksBlocks;
import wurmcraft.wurmatron.common.fluid.WurmTweaksFluid;
import wurmcraft.wurmatron.common.items.WurmTweaksItems;
import wurmcraft.wurmatron.common.recipes.RecipeHelper;
import wurmcraft.wurmatron.common.utils.buildcraft.BuildCraftHelper;
import wurmcraft.wurmatron.common.utils.nbt.ItemNBT;
import wurmcraft.wurmatron.common.utils.tfc.TFCHelper;
import wurmcraft.wurmatron.common.utils.thermalexpansion.TEHelper;

public class ThermalExpansionRecipes {


		private static RecipeHelper r = new RecipeHelper();

		@Optional.Method (modid = "ThermalExpansion")
		public static void addRecipes () {
				BuildCraftHelper.addAssemblerRecipes("te:basicmachineframe", 12000, BlockFrame.frameMachineBasic, WurmTweaksItems.itemMachineFrame, new ItemStack(EnderIO.itemBasicCapacitor, 4, 0), new ItemStack(TFCItems.blackSteelSheet, 4));
				BuildCraftHelper.addAssemblerRecipes("te:hardmachineframe", 240000, BlockFrame.frameMachineReinforced, new ItemStack(WurmTweaksItems.itemMachineFrame.getItem(), 2, 33), new ItemStack(EnderIO.itemBasicCapacitor, 4, 1), new ItemStack(TFCItems.redSteelSheet, 4));
				BuildCraftHelper.addAssemblerRecipes("te:reinforcedmachineframe", 1200000, BlockFrame.frameMachineReinforced, new ItemStack(WurmTweaksItems.itemMachineFrame.getItem(), 3, 33), new ItemStack(EnderIO.itemBasicCapacitor, 4, 2), new ItemStack(TFCItems.platinumSheet2x, 4));
				BuildCraftHelper.addAssemblerRecipes("te:enderiummachineframe", 12000000, BlockFrame.frameMachineResonant, new ItemStack(WurmTweaksItems.itemMachineFrame.getItem(), 4, 33), new ItemStack(EnderIO.itemBasicCapacitor, 4, 2), new ItemStack(TFCItems.platinumSheet2x, 4), TFItems.ingotEnderium);
				r.addShaped(ItemNBT.addDamage(new ItemStack(TEItems.itemBattleWrench), 280), "III", " I ", " I ", 'I', new ItemStack(TFCItems.steelSheet));
				r.addShaped(new ItemStack(TEItems.itemMaterial, 1, 16), " I ", "ICI", "III", 'I', new ItemStack(TFItems.itemMaterial, 1, 74), 'C', TFCItems.bronzeIngot);
				r.addShaped(TEHelper.getMagma("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getMagma("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getMagma("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getMagma("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.roseGoldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getFluid("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.goldSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getCobble("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getFluid("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFluid("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packCobblestone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAqua("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getAqua("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAqua("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAqua("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.wroughtIronSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAssembler("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getAssembler("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAssembler("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getAssembler("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', Blocks.crafting_table, 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPower("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGem");
				r.addShaped(TEHelper.getPower("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPower("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPower("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.silverSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(ItemNBT.addDamage(TEItems.toolWrench, 120), "I I", " T ", " I ", 'I', new ItemStack(TFCItems.wroughtIronIngot), 'T', new ItemStack(TFCItems.tinIngot));
				r.addShaped(TEItems.toolMultimeter, "C C", "LPL", " G ", 'C', new ItemStack(TFCItems.copperIngot), 'L', new ItemStack(TFCItems.leadIngot), 'P', cofh.thermalexpansion.item.TEItems.powerCoilElectrum, 'G', new ItemStack(TFCItems.roseGoldSheet2x));
				r.addShaped(TEItems.capacitorPotato, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.leadIngot), 'R', new ItemStack(Items.redstone), 'X', TFCHelper.getFood(TFCItems.potato, 160), 'Y', "dustSulfur");
				r.addShaped(TEItems.capacitorBasic, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.leadIngot), 'R', new ItemStack(Items.redstone), 'X', new ItemStack(TFCItems.blackSteelIngot), 'Y', "dustSulfur");
				r.addShaped(TEItems.capacitorHardened, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.nickelIngot), 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorBasic, 'Y', new ItemStack(TFCItems.blueSteelIngot));
				r.addShaped(TEItems.capacitorHardened, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.nickelIngot), 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorBasic, 'Y', new ItemStack(TFCItems.blueSteelIngot));
				r.addShaped(TEItems.capacitorReinforced, " R ", "IXI", "RYR", 'I', new ItemStack(TFCItems.roseGoldSheet), 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorHardened, 'Y', "packGemExquisite");
				r.addShaped(TEItems.capacitorResonant, " R ", "IXI", "RYR", 'I', TFItems.ingotEnderium, 'R', new ItemStack(Items.redstone), 'X', cofh.thermalexpansion.item.TEItems.capacitorReinforced, 'Y', TFItems.dustPyrotheum);
				r.addShaped(cofh.thermalexpansion.item.TEItems.satchelBasic, " Y ", "IXI", "Y Y", 'I', new ItemStack(TFCItems.bismuthSheet), 'X', new ItemStack(TFCItems.silkCloth), 'Y', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE));
				r.addShaped(TEItems.satchelHardened, " Y ", "IXI", "Y Y", 'I', new ItemStack(TFCItems.nickelIngot), 'X', cofh.thermalexpansion.item.TEItems.satchelBasic, 'Y', new ItemStack(TFCItems.zincIngot));
				TECraftingHandler.addSecureRecipe(TEItems.satchelCreative);
				TECraftingHandler.addSecureRecipe(TEItems.satchelBasic);
				TECraftingHandler.addSecureRecipe(TEItems.satchelHardened);
				TECraftingHandler.addSecureRecipe(TEItems.satchelReinforced);
				TECraftingHandler.addSecureRecipe(TEItems.satchelResonant);
				r.addShaped(TEItems.pneumaticServo, " I ", "GRG", " I ", 'R', new ItemStack(Items.redstone), 'G', "packGlass", 'I', new ItemStack(TFCItems.steelIngot));
				r.addShaped(TEItems.powerCoilGold, "  R", " G ", "R  ", 'R', new ItemStack(Items.redstone), 'G', new ItemStack(TFCItems.goldIngot));
				r.addShaped(TEItems.powerCoilSilver, "  R", " G ", "R  ", 'R', new ItemStack(Items.redstone), 'G', new ItemStack(TFCItems.silverIngot));
				r.addShaped(TEItems.powerCoilElectrum, "R  ", " G ", "  R", 'R', new ItemStack(Items.redstone), 'G', new ItemStack(TFCItems.roseGoldIngot));
				r.addShaped(TEAugments.generalAutoInput, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinIngot), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo);
				r.addShaped(TEAugments.generalAutoOutput, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinSheet), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo);
				r.addShaped(TEAugments.generalReconfigSides, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinSheet), 'X', new ItemStack(TFCItems.goldSheet));
				r.addShaped(TEAugments.generalRedstoneControl, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinSheet), 'X', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.dynamoCoilDuct, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.leadSheet), 'X', new ItemStack(TFCItems.copperIngot));
				r.addShaped(TEAugments.dynamoEfficiency[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.leadSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', new ItemStack(TFCItems.tinIngot), 'Y', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.dynamoEfficiency[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.leadSheet), 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', Items.glowstone_dust);
				r.addShaped(TEAugments.dynamoEfficiency[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', TFItems.dustCryotheum);
				r.addShaped(TEAugments.dynamoOutput[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.copperIngot), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.dynamoOutput[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.copperIngot), 'I', new ItemStack(TFCItems.silverSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', Items.glowstone_dust);
				r.addShaped(TEAugments.dynamoOutput[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.silverSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'Y', TFItems.dustCryotheum);
				r.addShaped(TEAugments.machineSecondary[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.brassIngot), 'X', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE), 'Y', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE));
				r.addShaped(TEAugments.machineSecondary[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.brassIngot), 'I', "packGlass", 'X', new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE), 'Y', Items.glowstone_dust);
				r.addShaped(TEAugments.machineSecondary[2], " I ", "IXI", "YIY", 'I', "packGlass", 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', TFItems.dustCryotheum);
				r.addShaped(TEAugments.machineSpeed[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.brassIngot), 'X', cofh.thermalexpansion.item.TEItems.powerCoilGold, 'Y', new ItemStack(Items.redstone));
				r.addShaped(TEAugments.machineSpeed[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.brassIngot), 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilGold, 'Y', TFItems.dustPyrotheum);
				r.addShaped(TEAugments.machineSpeed[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.powerCoilGold, 'Y', new ItemStack(Items.nether_star));
				r.addShaped(TEAugments.machineExtruderBoost[0], " N ", "NXN", "YNY", 'N', new ItemStack(TFCItems.brassIngot), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', "packGemExquisite");
				r.addShaped(TEAugments.machineExtruderBoost[1], " I ", "NXN", "YIY", 'N', new ItemStack(TFCItems.brassIngot), 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', Blocks.redstone_block);
				r.addShaped(TEAugments.machineExtruderBoost[2], " I ", "IXI", "YIY", 'I', new ItemStack(TFCItems.goldSheet), 'X', cofh.thermalexpansion.item.TEItems.pneumaticServo, 'Y', "packGemExquisite");
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoSteam, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.copperSheet2x), 'I', new ItemStack(TFCItems.copperIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoMagmatic, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.nickelSheet2x), 'I', new ItemStack(TFCItems.nickelIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoCompression, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.steelSheet2x), 'I', new ItemStack(TFCItems.steelIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoReactant, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.blackSteelSheet2x), 'I', new ItemStack(TFCItems.blackSteelIngot), 'R', new ItemStack(Items.redstone)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDynamo.dynamoEnervation, BlockDynamo.defaultAugments, new Object[] {" C ", "GIG", "IRI", 'C', cofh.thermalexpansion.item.TEItems.powerCoilSilver, 'G', new ItemStack(TFCItems.redSteelSheet2x), 'I', new ItemStack(TFCItems.redSteelIngot), 'R', new ItemStack(Items.redstone)}));
				r.addShaped(BlockCache.cacheHardened, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', BlockCache.cacheBasic);
				r.addShaped(BlockCache.cacheReinforced, " G ", "GXG", " G ", 'X', BlockCache.cacheHardened, 'G', "packGlass");
				r.addShaped(BlockCache.cacheResonant, " I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockCache.cacheReinforced);
				r.addShaped(BlockStrongbox.strongboxReinforced, " G ", "GXG", " G ", 'X', BlockStrongbox.strongboxHardened, 'G', "packGlass");
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDevice.breaker, BlockDevice.defaultAugments, new Object[] {" X ", "ICI", " P ", 'C', new ItemStack(TFCItems.copperIngot), 'I', new ItemStack(TFCItems.roseGoldIngot), 'P', TEItems.pneumaticServo, 'X', new ItemStack(TFCItems.redSteelPick)}));
				GameRegistry.addRecipe(new RecipeAugmentable(BlockDevice.nullifier, BlockDevice.defaultAugments, new Object[] {" X ", "ICI", " P ", 'C', "packChest", 'I', new ItemStack(TFCItems.blueSteelBucketLava), 'P', TEItems.pneumaticServo, 'X', new ItemStack(TFCItems.nickelIngot)}));
				GameRegistry.addRecipe(new RecipeUpgrade(BlockStrongbox.strongboxResonant, new Object[] {" I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockStrongbox.strongboxReinforced}));
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoSteam);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoMagmatic);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoCompression);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoEnervation);
				TECraftingHandler.addSecureRecipe(BlockDynamo.dynamoReactant);
				r.addShaped(BlockCache.cacheBasic, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.tinIngot), 'X', "packLog");
				r.addShaped(BlockCache.cacheHardened, "IYI", "YXY", "IYI", 'I', new ItemStack(TFCItems.roseGoldSheet), 'X', "packLog", 'Y', new ItemStack(TFCItems.tinIngot));
				r.addShaped(BlockTank.tankBasic, " G ", "GXG", " G ", 'G', "packGlass", 'X', new ItemStack(TFCItems.copperIngot));
				r.addShaped(BlockStrongbox.strongboxHardened, "IYI", "YXY", "IYI", 'I', new ItemStack(TFCItems.brassIngot), 'X', "packChest", 'Y', new ItemStack(TFCItems.steelIngot));
				GameRegistry.addRecipe(new RecipeUpgrade(BlockStrongbox.strongboxResonant, new Object[] {" I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockStrongbox.strongboxReinforced}));
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxCreative);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxBasic);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxHardened);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxReinforced);
				TECraftingHandler.addSecureRecipe(BlockStrongbox.strongboxResonant);
				r.addShaped(BlockEnder.tesseract, "BIB", "ICI", "BIB", 'C', BlockFrame.frameTesseractFull, 'I', new ItemStack(TFCItems.redSteelSheet2x), 'B', new ItemStack(TFCItems.blueSteelSheet2x));
				TECraftingHandler.addSecureRecipe(BlockEnder.tesseract);
				TECraftingHandler.addSecureRecipe(BlockCell.cellCreative);
				TECraftingHandler.addSecureRecipe(BlockCell.cellBasic);
				TECraftingHandler.addSecureRecipe(BlockCell.cellHardened);
				TECraftingHandler.addSecureRecipe(BlockCell.cellReinforced);
				TECraftingHandler.addSecureRecipe(BlockCell.cellResonant);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchBasic);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchHardened);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchReinforced);
				TECraftingHandler.addSecureRecipe(BlockWorkbench.workbenchResonant);
				TECraftingHandler.addSecureRecipe(BlockDevice.activator);
				TECraftingHandler.addSecureRecipe(BlockDevice.breaker);
				TECraftingHandler.addSecureRecipe(BlockDevice.nullifier);
				r.addShaped(BlockDevice.activator, "SPS", "ECE", "SXS", 'S', WurmTweaksItems.itemMixedSheet, 'P', new ItemStack(TFCItems.blueSteelPick), 'X', new ItemStack(TFCItems.redSteelShovel), 'E', "packGemExquisite", 'C', "packChest");
				r.addShaped(BlockCell.cellBasic, " I ", "IXI", " P ", 'I', new ItemStack(TFCItems.steelIngot), 'X', BlockFrame.frameCellBasic, 'P', TEItems.powerCoilElectrum);
				r.addShaped(BlockCell.cellHardened, " I ", "IXI", " P ", 'I', new ItemStack(TFCItems.steelIngot), 'X', BlockFrame.frameCellHardened, 'P', TEItems.powerCoilElectrum);
				r.addShaped(BlockCell.cellReinforced, " X ", "YCY", "IPI", 'C', BlockFrame.frameCellReinforcedFull, 'I', new ItemStack(TFCItems.leadIngot), 'P', TEItems.powerCoilElectrum, 'X', TFItems.ingotEnderium, 'Y', TFItems.ingotEnderium);
				r.addShaped(BlockCell.cellResonant, " X ", "YCY", "IPI", 'C', BlockFrame.frameCellResonantFull, 'I', new ItemStack(TFCItems.leadIngot), 'P', TEItems.powerCoilElectrum, 'X', TFItems.ingotEnderium, 'Y', TFItems.ingotEnderium);
				r.addShaped(BlockFrame.frameCellBasic, "IGI", "GXG", "IGI", 'I', new ItemStack(TFCItems.platinumIngot), 'G', "packGlass", 'X', Blocks.redstone_block);
				r.addShaped(BlockFrame.frameCellHardened, " I ", "IXI", " I ", 'I', new ItemStack(TFCItems.roseGoldIngot), 'X', BlockFrame.frameCellBasic);
				r.addShaped(BlockFrame.frameCellReinforcedEmpty, "IGI", "GXG", "IGI", 'I', TFItems.ingotEnderium, 'G', "packGlass", 'X', "packGemExquisite");
				r.addShaped(BlockFrame.frameCellResonantEmpty, " I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockFrame.frameCellReinforcedEmpty);
				r.addShaped(BlockFrame.frameCellResonantFull, " I ", "IXI", " I ", 'I', TFItems.ingotEnderium, 'X', BlockFrame.frameCellReinforcedFull);
				r.addShaped(BlockFrame.frameTesseractEmpty, "IGI", "GXG", "IGI", 'I', TFItems.ingotEnderium, 'G', "packGlass", 'X', "packGemExquisite");
				r.addShaped(BlockSponge.spongeBasic, "SWS", "WBW", "SWS", 'S', Items.string, 'W', "packLog", 'B', Items.slime_ball);
				r.addShaped(BlockSponge.spongeMagmatic, "SWS", "WBW", "SWS", 'S', Items.string, 'W', "packLog", 'B', Items.magma_cream);
				r.addShaped(BlockWorkbench.workbenchBasic, " X ", "ICI", " P ", 'C', Blocks.crafting_table, 'I', "ingotCopper", 'P', BlockStrongbox.strongboxBasic, 'X', Items.paper);
				for (int d = 0; d < 15; d++)
						r.addCircleWCenter(new ItemStack(BlockRockwool.rockWool.getItem(), 8, d), "blockClothRock", RecipeHelper.dye.get(d));
				r.addShaped(TEHelper.getFurnace("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFurnace("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFurnace("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getFurnace("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packSmoothStone", 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getPulveriser("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(Items.flint), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSawmill("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', "packPlanks", 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Basic"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 0), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Hardened"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 1), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Reinforced"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 2), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(TEHelper.getSmelter("Resonant"), " R ", "BCB", "GXG", 'R', new ItemStack(Items.redstone), 'B', new ItemStack(TFCItems.nickelSheet), 'C', new ItemStack(TEBlocks.blockFrame, 1, 3), 'G', WurmTweaksItems.itemMixedSheet, 'X', "packGemExquisite");
				r.addShaped(new ItemStack(TFItems.itemMaterial, 4, 512), "BGB", "RRR", "BGB", 'B', "dustSulfur", 'G', Items.gunpowder, 'R', Items.redstone);
				r.addShaped(new ItemStack(TFItems.itemMaterial, 4, 513), "BGB", "RRR", "BGB", 'B', new ItemStack(TFItems.itemMaterial, 1, 1025), 'G', "dustSulfur", 'R', Items.redstone);
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 4, 44), new ItemStack(TFItems.itemBucket, 1, 2), TFCItems.platinumSheet, TFCItems.redSteelSheet, WurmTweaksItems.gearMixedSheet);
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 4, 42), new ItemStack(TFItems.itemBucket, 1, 0), TFCItems.platinumSheet, TFCItems.redSteelSheet, WurmTweaksItems.gearMixedSheet);
				r.addShapeless(new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 4, 44), TFCItems.tinSheet, TFCItems.platinumSheet, TFCItems.tinSheet, TFCItems.wroughtIronSheet, TFItems.bucketEnder);
				r.addShapeless(new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 4, 42), TFCItems.tinSheet, TFCItems.platinumSheet, TFCItems.tinSheet, TFCItems.wroughtIronSheet, TFItems.bucketRedstone);
				r.addShapeless(new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 9, 106), new ItemStack(cofh.thermalexpansion.item.TEItems.itemMaterial, 1, 74));
				r.addShapeless(TEItems.diagramSchematic, Items.paper, Items.paper, "dyeBlue");
				r.addShapeless(TEItems.diagramRedprint, Items.paper, Items.paper, Items.redstone);
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 1, 74), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106), new ItemStack(TFItems.itemMaterial, 1, 106));
				r.addShapeless(new ItemStack(TFItems.itemMaterial, 9, 106), new ItemStack(TFItems.itemMaterial, 1, 74));
				r.addShaped9X9Recipe(new ItemStack(TEBlocks.blockCell, 1, 0), "CIIIIIIIC", "IBBBBBBBI", "IBXXXXXBI", "IBXXXXXBI", "IBXXXXXBI", "IBXXXXXBI", "IBXXXXXBI", "IBBBBBBBI", "CIIIIIIIC", 'C', WurmTweaksItems.creativeCreativePartsEnergy, 'I', new ItemStack(LudicrousItems.resource, 1, 5), 'B', new ItemStack(TEBlocks.blockCell, 1, 4), 'X', WurmTweaksItems.ingotRainbowSteel);
				r.addBasicMachineRecipe(TEItems.capacitorCreative, new ItemStack(LudicrousItems.resource, 1, 5), TEItems.capacitorResonant, WurmTweaksItems.creativeCreativeParts, new ItemStack(TEBlocks.blockCell, 1, 1));
				addFurnaceRecipes();
				addSawmillRecipes();
				addInductionSmelterRecipes();
				addMagmaCrucibleRecipes();
				addFluidTransposerRecipes();
		}

		private static void addFurnaceRecipes () {
				for (ItemStack logs : OreDictionary.getOres("packLog"))
						TEHelper.addFurnaceRecipe(12000, logs, new ItemStack(TFCItems.coal, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldAxe, 1, 0), new ItemStack(TFCItems.clayMoldAxe, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldChisel, 1, 0), new ItemStack(TFCItems.clayMoldChisel, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldHammer, 1, 0), new ItemStack(TFCItems.clayMoldHammer, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldHoe, 1, 0), new ItemStack(TFCItems.clayMoldHoe, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldJavelin, 1, 0), new ItemStack(TFCItems.clayMoldJavelin, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldKnife, 1, 0), new ItemStack(TFCItems.clayMoldKnife, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldMace, 1, 0), new ItemStack(TFCItems.clayMoldMace, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldPick, 1, 0), new ItemStack(TFCItems.clayMoldPick, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldProPick, 1, 0), new ItemStack(TFCItems.clayMoldProPick, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldSaw, 1, 0), new ItemStack(TFCItems.clayMoldSaw, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldScythe, 1, 0), new ItemStack(TFCItems.clayMoldScythe, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldShovel, 1, 0), new ItemStack(TFCItems.clayMoldShovel, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.clayMoldSword, 1, 0), new ItemStack(TFCItems.clayMoldSword, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.fireBrick, 1, 0), new ItemStack(TFCItems.fireBrick, 1, 1));
				TEHelper.addFurnaceRecipe(4000, new ItemStack(TFCItems.ceramicMold, 1, 0), new ItemStack(TFCItems.ceramicMold, 1, 1));
		}

		private static void addSawmillRecipes () {
				for (int l = 0; l < 16; l++)
						TEHelper.addFurnaceRecipe(8000, new ItemStack(TFCItems.logs, 1, l), new ItemStack(TFCItems.singlePlank, 6, 1));
		}

		private static void addInductionSmelterRecipes () {
				TEHelper.addSmelterRecipe(12000, new ItemStack(TFCItems.wroughtIronIngot), new ItemStack(TFCItems.coal, 4, 1), new ItemStack(TFCItems.steelIngot));
				TEHelper.addSmelterRecipe(240000, new ItemStack(TFCItems.wroughtIronIngot2x), new ItemStack(TFCItems.coal, 4, 1), new ItemStack(TFCItems.steelIngot2x));
				TEHelper.addSmelterRecipe(24000, new ItemStack(TFCItems.wroughtIronSheet), new ItemStack(TFCItems.coal, 4, 1), new ItemStack(TFCItems.steelSheet));
				TEHelper.addSmelterRecipe(48000, new ItemStack(TFCItems.wroughtIronSheet2x), new ItemStack(TFCItems.coal, 16, 1), new ItemStack(TFCItems.steelSheet2x));
				TEHelper.addSmelterRecipe(380000, new ItemStack(WurmTweaksBlocks.blockWroughtIron), new ItemStack(TFCItems.coal, 64, 1), new ItemStack(WurmTweaksBlocks.blockSteel));
		}

		public static void addMagmaCrucibleRecipes () {
				// TODO Disabled due to skipping smeltery
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthIngot), new FluidStack(WurmTweaksFluid.fluidBismuth, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthBronzeIngot), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackBronzeIngot), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackSteelIngot), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blueSteelIngot), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.brassIngot), new FluidStack(WurmTweaksFluid.fluidBrass, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bronzeIngot), new FluidStack(WurmTweaksFluid.fluidBronze, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.copperIngot), new FluidStack(WurmTweaksFluid.fluidCopper, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.goldIngot), new FluidStack(WurmTweaksFluid.fluidGold, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.wroughtIronIngot), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.leadIngot), new FluidStack(WurmTweaksFluid.fluidLead, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.nickelIngot), new FluidStack(WurmTweaksFluid.fluidNickel, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.pigIronIngot), new FluidStack(WurmTweaksFluid.fluidPigIron, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.platinumIngot), new FluidStack(WurmTweaksFluid.fluidPlatinum, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.redSteelIngot), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.roseGoldIngot), new FluidStack(WurmTweaksFluid.fluidRoseGold, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.silverIngot), new FluidStack(WurmTweaksFluid.fluidSilver, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.steelIngot), new FluidStack(WurmTweaksFluid.fluidSteel, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.sterlingSilverIngot), new FluidStack(WurmTweaksFluid.fluidSterlingSilver, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.tinIngot), new FluidStack(WurmTweaksFluid.fluidTin, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.zincIngot), new FluidStack(WurmTweaksFluid.fluidZinc, 1000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthSheet), new FluidStack(WurmTweaksFluid.fluidBismuth, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthBronzeSheet), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackBronzeSheet), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackSteelSheet), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blueSteelSheet), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.brassSheet), new FluidStack(WurmTweaksFluid.fluidBrass, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bronzeSheet), new FluidStack(WurmTweaksFluid.fluidBronze, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.copperSheet), new FluidStack(WurmTweaksFluid.fluidCopper, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.goldSheet), new FluidStack(WurmTweaksFluid.fluidGold, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.wroughtIronSheet), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.leadSheet), new FluidStack(WurmTweaksFluid.fluidLead, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.nickelSheet), new FluidStack(WurmTweaksFluid.fluidNickel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.pigIronSheet), new FluidStack(WurmTweaksFluid.fluidPigIron, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.platinumSheet), new FluidStack(WurmTweaksFluid.fluidPlatinum, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.redSteelSheet), new FluidStack(WurmTweaksFluid.fluidRedSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.roseGoldSheet), new FluidStack(WurmTweaksFluid.fluidRoseGold, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.silverSheet), new FluidStack(WurmTweaksFluid.fluidSilver, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.steelSheet), new FluidStack(WurmTweaksFluid.fluidSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.sterlingSilverSheet), new FluidStack(WurmTweaksFluid.fluidSterlingSilver, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.tinSheet), new FluidStack(WurmTweaksFluid.fluidTin, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.zincSheet), new FluidStack(WurmTweaksFluid.fluidZinc, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthIngot2x), new FluidStack(WurmTweaksFluid.fluidBismuth, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthBronzeIngot2x), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackBronzeIngot2x), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackSteelIngot2x), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blueSteelIngot2x), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.brassIngot2x), new FluidStack(WurmTweaksFluid.fluidBrass, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bronzeIngot2x), new FluidStack(WurmTweaksFluid.fluidBronze, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.copperIngot2x), new FluidStack(WurmTweaksFluid.fluidCopper, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.goldIngot2x), new FluidStack(WurmTweaksFluid.fluidGold, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.wroughtIronIngot2x), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.leadIngot2x), new FluidStack(WurmTweaksFluid.fluidLead, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.nickelIngot2x), new FluidStack(WurmTweaksFluid.fluidNickel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.pigIronIngot2x), new FluidStack(WurmTweaksFluid.fluidPigIron, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.platinumIngot2x), new FluidStack(WurmTweaksFluid.fluidPlatinum, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.redSteelIngot2x), new FluidStack(WurmTweaksFluid.fluidRedSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.roseGoldIngot2x), new FluidStack(WurmTweaksFluid.fluidRoseGold, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.silverIngot2x), new FluidStack(WurmTweaksFluid.fluidSilver, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.steelIngot2x), new FluidStack(WurmTweaksFluid.fluidSteel, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.sterlingSilverIngot2x), new FluidStack(WurmTweaksFluid.fluidSterlingSilver, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.tinIngot2x), new FluidStack(WurmTweaksFluid.fluidTin, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.zincIngot2x), new FluidStack(WurmTweaksFluid.fluidZinc, 2000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthSheet2x), new FluidStack(WurmTweaksFluid.fluidBismuth, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bismuthBronzeSheet2x), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackBronzeSheet2x), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blackSteelSheet2x), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.blueSteelSheet2x), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.brassSheet2x), new FluidStack(WurmTweaksFluid.fluidBrass, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.bronzeSheet2x), new FluidStack(WurmTweaksFluid.fluidBronze, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.copperSheet2x), new FluidStack(WurmTweaksFluid.fluidCopper, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.goldSheet2x), new FluidStack(WurmTweaksFluid.fluidGold, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.wroughtIronSheet2x), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.leadSheet2x), new FluidStack(WurmTweaksFluid.fluidLead, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.nickelSheet2x), new FluidStack(WurmTweaksFluid.fluidNickel, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.pigIronSheet2x), new FluidStack(WurmTweaksFluid.fluidPigIron, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.platinumSheet2x), new FluidStack(WurmTweaksFluid.fluidPlatinum, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.redSteelSheet2x), new FluidStack(WurmTweaksFluid.fluidRedSteel, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.roseGoldSheet2x), new FluidStack(WurmTweaksFluid.fluidRoseGold, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.silverSheet2x), new FluidStack(WurmTweaksFluid.fluidSilver, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.steelSheet2x), new FluidStack(WurmTweaksFluid.fluidSteel, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.sterlingSilverSheet2x), new FluidStack(WurmTweaksFluid.fluidSterlingSilver, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.tinSheet2x), new FluidStack(WurmTweaksFluid.fluidTin, 4000));
//				TEHelper.addCrucibleRecipe(8000, new ItemStack(TFCItems.zincSheet2x), new FluidStack(WurmTweaksFluid.fluidZinc, 4000));
				for (ItemStack cobble : OreDictionary.getOres("packCobblestone"))
						TEHelper.addCrucibleRecipe(20000, cobble, new FluidStack(FluidRegistry.LAVA, 500));
		}

		private static void addFluidTransposerRecipes () {
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.bismuthUnshaped), new FluidStack(WurmTweaksFluid.fluidBismuth, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.bismuthBronzeUnshaped), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.blackBronzeUnshaped), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.blackSteelUnshaped), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.blueSteelUnshaped), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.brassUnshaped), new FluidStack(WurmTweaksFluid.fluidBrass, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.bronzeUnshaped), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.copperUnshaped), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.goldUnshaped), new FluidStack(WurmTweaksFluid.fluidGold, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.wroughtIronUnshaped), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.leadUnshaped), new FluidStack(WurmTweaksFluid.fluidLead, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.nickelUnshaped), new FluidStack(WurmTweaksFluid.fluidNickel, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.pigIronUnshaped), new FluidStack(WurmTweaksFluid.fluidPigIron, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.platinumUnshaped), new FluidStack(WurmTweaksFluid.fluidPlatinum, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.redSteelUnshaped), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.roseGoldUnshaped), new FluidStack(WurmTweaksFluid.fluidRoseGold, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.silverUnshaped), new FluidStack(WurmTweaksFluid.fluidSilver, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.steelUnshaped), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.sterlingSilverUnshaped), new FluidStack(WurmTweaksFluid.fluidSterlingSilver, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.tinUnshaped), new FluidStack(WurmTweaksFluid.fluidTin, 1000), false);
				TEHelper.addTransposerFill(4000, new ItemStack(TFCItems.ceramicMold, 1, 1), new ItemStack(TFCItems.zincUnshaped), new FluidStack(WurmTweaksFluid.fluidZinc, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castBismuth, new FluidStack(WurmTweaksFluid.fluidBismuth, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castBismuthBronze, new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castBlackBronze, new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castBlackSteel, new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castBlueSteel, new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castBrass, new FluidStack(WurmTweaksFluid.fluidBrass, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castBronze, new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castCopper, new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castGold, new FluidStack(WurmTweaksFluid.fluidGold, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castWroughtIron, new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castLead, new FluidStack(WurmTweaksFluid.fluidLead, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castNickel, new FluidStack(WurmTweaksFluid.fluidNickel, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castPigIron, new FluidStack(WurmTweaksFluid.fluidPigIron, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castPlatinum, new FluidStack(WurmTweaksFluid.fluidPlatinum, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castRedSteel, new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castRoseGold, new FluidStack(WurmTweaksFluid.fluidRoseGold, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castSilver, new FluidStack(WurmTweaksFluid.fluidSilver, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castSteel, new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castSterlingSilver, new FluidStack(WurmTweaksFluid.fluidSterlingSilver, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castTin, new FluidStack(WurmTweaksFluid.fluidTin, 1000), false);
				TEHelper.addTransposerFill(4000, WurmTweaksItems.castMetal, WurmTweaksItems.castZinc, new FluidStack(WurmTweaksFluid.fluidZinc, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.copperSwordHead), new FluidStack(WurmTweaksFluid.fluidCopper, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.wroughtIronSword), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.bronzeSwordHead), new FluidStack(WurmTweaksFluid.fluidBronze, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.blackSteelSwordHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.redSteelSwordHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.blueSteelSwordHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.steelSwordHead), new FluidStack(WurmTweaksFluid.fluidSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.bismuthBronzeSwordHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSword, 1, 1), new ItemStack(TFCItems.blackBronzeSwordHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.copperAxeHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.wroughtIronAxe), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.bronzeAxeHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.blackSteelAxeHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.redSteelAxeHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.blueSteelAxeHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.steelAxeHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.bismuthBronzeAxeHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldAxe, 1, 1), new ItemStack(TFCItems.blackBronzeAxeHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.copperChiselHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.wroughtIronChisel), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.bronzeChiselHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.blackSteelChiselHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.redSteelChiselHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.blueSteelChiselHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.steelChiselHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.bismuthBronzeChiselHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldChisel, 1, 1), new ItemStack(TFCItems.blackBronzeChiselHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.copperHammerHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.wroughtIronHammer), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.bronzeHammerHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.blackSteelHammerHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.redSteelHammerHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.blueSteelHammerHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.steelHammerHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.bismuthBronzeHammerHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHammer, 1, 1), new ItemStack(TFCItems.blackBronzeHammerHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.copperHoeHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.wroughtIronHoe), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.bronzeHoeHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.blackSteelHoeHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.redSteelHoeHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.blueSteelHoeHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.steelHoeHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.bismuthBronzeHoeHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldHoe, 1, 1), new ItemStack(TFCItems.blackBronzeHoeHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.copperJavelinHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.wroughtIronJavelin), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.bronzeJavelinHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.blackSteelJavelinHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.redSteelJavelinHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.blueSteelJavelinHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.steelJavelinHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.bismuthBronzeJavelinHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldJavelin, 1, 1), new ItemStack(TFCItems.blackBronzeJavelinHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.copperKnifeHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.wroughtIronKnife), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.bronzeKnifeHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.blackSteelKnifeHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.redSteelKnifeHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.blueSteelKnifeHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.steelKnifeHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.bismuthBronzeKnifeHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldKnife, 1, 1), new ItemStack(TFCItems.blackBronzeKnifeHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.copperMaceHead), new FluidStack(WurmTweaksFluid.fluidCopper, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.wroughtIronMace), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.bronzeMaceHead), new FluidStack(WurmTweaksFluid.fluidBronze, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.blackSteelMaceHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.redSteelMaceHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.blueSteelMaceHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.steelMaceHead), new FluidStack(WurmTweaksFluid.fluidSteel, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.bismuthBronzeMaceHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldMace, 1, 1), new ItemStack(TFCItems.blackBronzeMaceHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 2000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.copperPickaxeHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.wroughtIronPickaxeHead), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.bronzePickaxeHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.blackSteelPickaxeHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.redSteelPickaxeHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.blueSteelPickaxeHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.steelPickaxeHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.bismuthBronzePickaxeHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldPick, 1, 1), new ItemStack(TFCItems.blackBronzePickaxeHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.copperProPickHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.wroughtIronProPickHead), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.bronzeProPickHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.blackSteelProPickHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.redSteelProPickHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.blueSteelProPickHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.steelProPickHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.bismuthBronzeProPickHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldProPick, 1, 1), new ItemStack(TFCItems.blackBronzeProPickHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.copperSawHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.wroughtIronSaw), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.bronzeSawHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.blackSteelSawHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.redSteelSawHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.blueSteelSawHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.steelSawHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.bismuthBronzeSawHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldSaw, 1, 1), new ItemStack(TFCItems.blackBronzeSawHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.copperScytheHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.wroughtIronScythe), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.bronzeScytheHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.blackSteelScytheHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.redSteelScytheHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.blueSteelScytheHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.steelScytheHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.bismuthBronzeScytheHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldScythe, 1, 1), new ItemStack(TFCItems.blackBronzeScytheHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.copperShovelHead), new FluidStack(WurmTweaksFluid.fluidCopper, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.wroughtIronShovel), new FluidStack(WurmTweaksFluid.fluidWroughtIron, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.bronzeShovelHead), new FluidStack(WurmTweaksFluid.fluidBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.blackSteelShovelHead), new FluidStack(WurmTweaksFluid.fluidBlackSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.redSteelShovelHead), new FluidStack(WurmTweaksFluid.fluidRedSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.blueSteelShovelHead), new FluidStack(WurmTweaksFluid.fluidBlueSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.steelShovelHead), new FluidStack(WurmTweaksFluid.fluidSteel, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.bismuthBronzeShovelHead), new FluidStack(WurmTweaksFluid.fluidBismuthBronze, 1000), false);
				TEHelper.addTransposerFill(10000, new ItemStack(TFCItems.clayMoldShovel, 1, 1), new ItemStack(TFCItems.blackBronzeShovelHead), new FluidStack(WurmTweaksFluid.fluidBlackBronze, 1000), false);
		}
}
