package wurmcraft.wurmatron.common.recipes.mods;

import advsolar.common.AdvancedSolarPanel;
import buildcraft.BuildCraftCore;
import cofh.thermalexpansion.block.TEBlocks;
import cofh.thermalexpansion.block.cell.BlockCell;
import cofh.thermalexpansion.item.TEItems;
import cofh.thermalfoundation.item.TFItems;
import com.bioxx.tfc.api.TFCItems;
import com.rwtema.extrautils.ExtraUtils;
import crazypants.enderio.EnderIO;
import dan200.QCraft;
import erogenousbeef.bigreactors.common.BigReactors;
import fox.spiteful.avaritia.blocks.LudicrousBlocks;
import fox.spiteful.avaritia.items.LudicrousItems;
import ic2.api.item.IC2Items;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;
import thaumcraft.common.config.ConfigBlocks;
import thaumcraft.common.config.ConfigItems;
import vazkii.botania.common.item.ModItems;
import wurmcraft.wurmatron.common.blocks.WurmTweaksBlocks;
import wurmcraft.wurmatron.common.items.WTItems;
import wurmcraft.wurmatron.common.items.WurmTweaksItems;
import wurmcraft.wurmatron.common.recipes.RecipeHelper;
import wurmcraft.wurmatron.common.utils.LogHandler;
import wurmcraft.wurmatron.common.utils.ic2.ICHelper;
import wurmcraft.wurmatron.common.utils.machines.MachineHelper;
import wurmcraft.wurmatron.common.utils.tfc.TFCHelper;

public class WurmTweaksRecipes {

		private static final RecipeHelper r = new RecipeHelper();

		public static void addRecipes () {
				LogHandler.info("Adding WurmTweaks Recipes");
				r.addCrossWCenter(WurmTweaksItems.itemAutoCore, WurmTweaksItems.ingotFrancium, WurmTweaksItems.ingotEnergyReactor, "packCraftingTable");
				r.addShaped(WurmTweaksItems.itemSolarCore, "SSS", "PPP", "XXX", 'S', "packGlass", 'P', TFCItems.platinumSheet2x, 'X', "packCloth");
				r.addBasicMachineRecipe(WurmTweaksItems.itemCraftingCore, WurmTweaksItems.itemMixedSheet, "packCraftingTable", ExtraUtils.bedrockium, "packGemExquisite");
				r.addShapeless(WurmTweaksItems.ingotGreenSteel, new ItemStack(ModItems.manaResource, 1, 4), WurmTweaksItems.itemMixedSheet);
				r.addBasicMachineRecipe(WurmTweaksItems.ingotEnergyReactor, ExtraUtils.bedrockiumBlock, WurmTweaksItems.itemElectroMagneticShielding, BlockCell.cellResonant, "packGemBlock");
				r.addCrossWCenter(WurmTweaksItems.itemMixedSheet, TFCItems.redSteelSheet2x, TFCItems.blueSteelSheet2x, WurmTweaksItems.ingotPurpleSteel);
				r.addBasicMachineRecipe(WurmTweaksItems.ingotPinkSteel, "dyePink", WurmTweaksItems.ingotCyanSteel, WurmTweaksItems.gearMixedSheet, WurmTweaksItems.ingotPurpleSteel);
				r.addCrossWCenter(WurmTweaksItems.ingotYellowSteel, WurmTweaksItems.itemMixedSheet, "dyeYellow", WurmTweaksItems.itemCraftingCore);
				r.addCrossWCenter(WurmTweaksItems.ingotOrangeSteel, "dyeOrange", WurmTweaksItems.itemMixedSheet, WurmTweaksItems.itemCraftingCore);
				r.addCrossWCenter(WurmTweaksItems.ingotPurpleSteel, TFCItems.redSteelIngot, TFCItems.blueSteelIngot, "packGem");
				r.addShapeless(WurmTweaksItems.ingotCyanSteel, WurmTweaksItems.itemMixedSheet, "dyeCyan");
				r.addCrossWCenter(WurmTweaksItems.ingotBrownSteel, "dyeBrown", WurmTweaksItems.itemMixedSheet, WurmTweaksItems.itemCraftingCore);
				r.addBasicMachineRecipe(WurmTweaksItems.ingotGraySteel, TFCItems.blackSteelSheet2x, TFCItems.steelSheet2x, "packGemExquisite", WurmTweaksItems.itemMixedSheet);
				r.addShapeless(WurmTweaksItems.ingotRainbowSteel, WurmTweaksItems.ingotCyanSteel, WurmTweaksItems.ingotYellowSteel, WurmTweaksItems.ingotGreenSteel, WurmTweaksItems.itemCraftingCore, new ItemStack(EnderIO.itemAlloy, 1, 2), TFItems.ingotEnderium, com.brandon3055.draconicevolution.common.ModItems.draconicIngot, new ItemStack(ModItems.manaResource, 1, 14), IC2Items.getItem("iridiumPlate"));
				r.addBasicMachineRecipe(WurmTweaksItems.itemMagicChunk, WurmTweaksItems.itemCraftingCore, Items.ghast_tear, Items.glowstone_dust, ExtraUtils.bedrockium);
				r.addCrossWCenter(WurmTweaksItems.itemQuantumCore, WurmTweaksItems.itemQuantumFoam, WurmTweaksItems.itemCraftingCore, WurmTweaksItems.itemQuantumSingularity);
				r.addCrossWCenter(WurmTweaksItems.itemQuantumSingularity, ExtraUtils.bedrockium, "packGemExquisite", WurmTweaksItems.itemMixedSheet);
				r.addBasicMachineRecipe(WurmTweaksItems.itemQuantumFoam, QCraft.Items.quantumDust, ExtraUtils.bedrockium, Items.glowstone_dust, Items.redstone);
				MachineHelper.addFurnaceRecipes(WurmTweaksItems.ingotFrancium, new ItemStack(WurmTweaksBlocks.oreFrancium));
				MachineHelper.addFurnaceRecipes(WurmTweaksItems.ingotHalfium, new ItemStack(WurmTweaksBlocks.oreHalfium));
				MachineHelper.addFurnaceRecipes(WurmTweaksItems.ingotTitanium, new ItemStack(WurmTweaksBlocks.oreTitanium));
				r.addBasicMachineRecipe(WurmTweaksItems.itemRadiationShielding, TFCItems.leadSheet2x, WurmTweaksItems.ingotYellowSteel, WurmTweaksItems.itemMixedSheet, Items.redstone);
				r.addCrossWCenter(WurmTweaksItems.stableMagicEssence, WurmTweaksItems.itemMagicChunk, WurmTweaksItems.ingotGreenSteel, TFCItems.redSteelSheet2x);
				r.addBasicMachineRecipe(WurmTweaksItems.itemElectroShielding, WurmTweaksItems.itemRadiationShielding, TFItems.ingotEnderium, TEItems.capacitorResonant, WurmTweaksItems.itemMixedSheet);
				r.addCrossWCenter(WurmTweaksItems.itemBloodInfused, WurmTweaksItems.stableMagicEssence, WayofTime.alchemicalWizardry.ModItems.reinforcedSlate, WayofTime.alchemicalWizardry.ModItems.weakBloodShard);
				r.addCrossWCenter(WurmTweaksItems.itemNatureCore, WurmTweaksItems.itemMagicChunk, new ItemStack(ModItems.manaResource, 1, 0), WurmTweaksItems.itemCraftingCore);
				r.addCrossWCenter(WurmTweaksItems.itemNatureCoreMK2, WurmTweaksItems.itemNatureCore, WurmTweaksItems.ingotGreenSteel, new ItemStack(ModItems.manaResource, 1, 14));
				r.addShaped(WurmTweaksItems.itemEngineCoil, "XXX", " G ", "BAB", 'X', TFCItems.roseGoldSheet2x, 'G', TFCItems.platinumIngot, 'B', Items.redstone, 'A', TFCItems.blackSteelSheet2x);
				r.addCrossWCenter(WurmTweaksItems.itemQuarryCore, "packGemExquisite", ExtraUtils.bedrockium, WurmTweaksItems.itemMiningCore);
				r.addSimpleCirc(WurmTweaksItems.gearMixedSheet, WurmTweaksItems.itemMixedSheet, BuildCraftCore.diamondGearItem);
				r.addBasicMachineRecipe(WurmTweaksItems.itemMiningCore, TFCItems.blackSteelSheet2x, WurmTweaksItems.itemMixedSheet, TFCItems.redSteelPick, Items.redstone);
				r.addBasicMachineRecipe(WurmTweaksItems.itemMiningCore, TFCItems.blackSteelSheet2x, WurmTweaksItems.itemMixedSheet, TFCItems.blueSteelPick, Items.redstone);
				r.addBasicMachineRecipe(WurmTweaksItems.itemRefiningModule, TFCItems.blackSteelSheet2x, WurmTweaksItems.itemMixedSheet, TFCItems.clayBall, Items.redstone);
				r.addBasicMachineRecipe(WurmTweaksItems.itemComputationalCore, WurmTweaksItems.itemAutoCore, ExtraUtils.bedrockium, Items.redstone, WurmTweaksBlocks.blockCompressedRedstone);
				r.addBasicMachineRecipe(WurmTweaksItems.itemMachineFrame, TFCItems.blackSteelSheet2x, TFCItems.roseGoldSheet2x, WurmTweaksItems.itemMixedSheet, Items.redstone);
				r.addBasicMachineRecipe(WurmTweaksItems.itemSpaceModule, WurmTweaksBlocks.blockCompressedRedstone, WurmTweaksItems.itemMachineFrame, WurmTweaksItems.itemMixedSheet, Items.nether_star);
				r.addCrossWCenter(WurmTweaksItems.itemUnstableMatter, WurmTweaksItems.itemAntiMatter, WurmTweaksItems.ingotRainbowSteel, Items.redstone);
				r.addBasicMachineRecipe(WurmTweaksItems.itemJetpackParts, "dye", WurmTweaksItems.itemCraftingCore, WurmTweaksItems.ingotEnergyReactor, WurmTweaksItems.ingotGraySteel);
				r.addCrossWCenter(WurmTweaksItems.itemElectroMagneticShielding, WurmTweaksItems.itemElectroShielding, WurmTweaksItems.itemRadiationShielding, WurmTweaksBlocks.blockCompressedRedstone);
				r.addBasicMachineRecipe(WurmTweaksItems.itemWandParts, new ItemStack(ConfigBlocks.blockMagicalLog, 1, 1), WurmTweaksItems.itemCraftingCore, WurmTweaksItems.ingotEnergyReactor, new ItemStack(ConfigItems.itemResource, 1, 0));
				r.addSimpleCirc(new ItemStack(WurmTweaksItems.foodFruit.getItem(), 8, 0), "packFruit", "packFruit");
				r.addSimpleCirc(new ItemStack(WurmTweaksItems.foodGrain.getItem(), 8, 1), "packGrain", "packGrain");
				r.addSimpleCirc(new ItemStack(WurmTweaksItems.foodMeat.getItem(), 8, 2), "packMeat", "packMeat");
				r.addSimpleCirc(new ItemStack(WurmTweaksItems.foodVegtable.getItem(), 8, 3), "packVegetable", "packVegetable");
				r.addSimpleCirc(new ItemStack(WurmTweaksItems.foodCheese.getItem(), 8, 4), TFCHelper.getFood(TFCItems.cheese, 160), TFCItems.woodenBucketMilk);
				r.addShapeless(new ItemStack(WTItems.itemBasicFood, 1, 5), Items.skull, new ItemStack(WurmTweaksItems.foodMeat.getItem(), 1, 1));
				r.addSimpleCirc(new ItemStack(WTItems.itemBasicFood, 8, 6), new ItemStack(WurmTweaksItems.foodGrain.getItem(), 1, 1), new ItemStack(WurmTweaksItems.foodGrain.getItem(), 1, 1));
				r.addSimpleCirc(new ItemStack(WTItems.itemBasicFood, 5, 7), new ItemStack(WurmTweaksItems.foodGrain.getItem(), 1, 1), new ItemStack(WurmTweaksItems.foodCheese.getItem(), 1, 4));
				r.addSimpleCirc(new ItemStack(WTItems.itemBasicFood, 5, 8), new ItemStack(WurmTweaksItems.foodGrain.getItem(), 1, 1), new ItemStack(Items.skull, 1, OreDictionary.WILDCARD_VALUE));
				r.addShapeless(new ItemStack(WTItems.itemBasicFood, 5, 9), WurmTweaksItems.foodFruit, WurmTweaksItems.foodGrain, WurmTweaksItems.foodMeat, WurmTweaksItems.foodVegtable, WurmTweaksItems.foodCheese);
				r.addShapeless(new ItemStack(TFCItems.wroughtIronIngot, 32), new ItemStack(WurmTweaksBlocks.blockWroughtIron));
				r.addShapeless(new ItemStack(TFCItems.platinumIngot, 32), new ItemStack(WurmTweaksBlocks.blockPlatinum));
				r.addShapeless(new ItemStack(TFCItems.goldIngot, 32), new ItemStack(WurmTweaksBlocks.blockGold));
				r.addShapeless(new ItemStack(TFCItems.sterlingSilverIngot, 32), new ItemStack(WurmTweaksBlocks.blockSterlingSilver));
				r.addShapeless(new ItemStack(TFCItems.silverIngot, 32), new ItemStack(WurmTweaksBlocks.blockSilver));
				r.addShapeless(new ItemStack(TFCItems.blueSteelIngot, 32), new ItemStack(WurmTweaksBlocks.blockBlueSteel));
				r.addShapeless(new ItemStack(TFCItems.blackSteelIngot, 32), new ItemStack(WurmTweaksBlocks.blockBlackSteel));
				r.addShapeless(new ItemStack(TFCItems.redSteelIngot, 32), new ItemStack(WurmTweaksBlocks.blockRedSteel));
				r.addShapeless(new ItemStack(TFCItems.copperIngot, 32), new ItemStack(WurmTweaksBlocks.blockCopper));
				r.addShapeless(new ItemStack(TFCItems.steelIngot, 32), new ItemStack(WurmTweaksBlocks.blockSteel));
				r.addShapeless(new ItemStack(TFCItems.bronzeIngot, 32), new ItemStack(WurmTweaksBlocks.blockBronze));
				r.addShapeless(new ItemStack(TFCItems.bismuthIngot, 32), new ItemStack(WurmTweaksBlocks.blockBismuth));
				r.addShapeless(new ItemStack(TFCItems.bismuthBronzeIngot, 32), new ItemStack(WurmTweaksBlocks.blockBismuthBronze));
				r.addShapeless(new ItemStack(TFCItems.blackBronzeIngot, 32), new ItemStack(WurmTweaksBlocks.blockBlackBronze));
				r.addShapeless(new ItemStack(TFCItems.brassIngot, 32), new ItemStack(WurmTweaksBlocks.blockBrass));
				r.addShapeless(new ItemStack(TFCItems.leadIngot, 32), new ItemStack(WurmTweaksBlocks.blockLead));
				r.addShapeless(new ItemStack(TFCItems.nickelIngot, 32), new ItemStack(WurmTweaksBlocks.blockNickel));
				r.addShapeless(new ItemStack(TFCItems.pigIronIngot, 32), new ItemStack(WurmTweaksBlocks.blockPigIron));
				r.addShapeless(new ItemStack(TFCItems.roseGoldIngot, 32), new ItemStack(WurmTweaksBlocks.blockRoseGold));
				r.addShapeless(new ItemStack(TFCItems.zincIngot, 32), new ItemStack(WurmTweaksBlocks.blockZinc));
				r.addShapeless(new ItemStack(TFCItems.tinIngot, 32), new ItemStack(WurmTweaksBlocks.blockTin));
				r.addShapeless(new ItemStack(TFCItems.unknownIngot, 32), new ItemStack(WurmTweaksBlocks.blockUnkown));
				r.addShapeless(new ItemStack(TFCItems.gemJasper, 32, 4), new ItemStack(WurmTweaksBlocks.blockJasper));
				r.addShapeless(new ItemStack(TFCItems.gemAmethyst, 32, 4), new ItemStack(WurmTweaksBlocks.blockAmethyst));
				r.addShapeless(new ItemStack(TFCItems.gemDiamond, 32, 4), new ItemStack(WurmTweaksBlocks.blockDiamond));
				r.addShapeless(new ItemStack(TFCItems.gemRuby, 32, 4), new ItemStack(WurmTweaksBlocks.blockRuby));
				r.addShapeless(new ItemStack(TFCItems.gemSapphire, 32, 4), new ItemStack(WurmTweaksBlocks.blockSapphire));
				r.addShapeless(new ItemStack(TFCItems.gemEmerald, 32, 4), new ItemStack(WurmTweaksBlocks.blockEmerald));
				r.addShapeless(new ItemStack(TFCItems.gemTopaz, 32, 4), new ItemStack(WurmTweaksBlocks.blockTopaz));
				r.addShapeless(new ItemStack(TFCItems.gemTourmaline, 32, 4), new ItemStack(WurmTweaksBlocks.blockTourmaline));
				r.addShapeless(new ItemStack(TFCItems.gemJade, 32, 4), new ItemStack(WurmTweaksBlocks.blockJade));
				r.addShapeless(new ItemStack(TFCItems.gemAgate, 32, 4), new ItemStack(WurmTweaksBlocks.blockAgate));
				r.addShapeless(new ItemStack(TFCItems.gemOpal, 32, 4), new ItemStack(WurmTweaksBlocks.blockOpal));
				r.addShapeless(new ItemStack(TFCItems.gemGarnet, 32, 4), new ItemStack(WurmTweaksBlocks.blockGarnet));
				r.addSimpleCirc(new ItemStack(WTItems.itemJug_2), TFCItems.leather, new ItemStack(TFCItems.potteryJug, 1, 1));
				r.addSimpleCirc(new ItemStack(WTItems.itemJug_2), TFCItems.leather, new ItemStack(TFCItems.potteryJug, 1, 2));
				r.addShapeless(new ItemStack(WTItems.itemJug_4), new ItemStack(WTItems.itemJug_2), new ItemStack(WTItems.itemJug_2));
				r.addShapeless(new ItemStack(WTItems.itemJug_6), new ItemStack(WTItems.itemJug_2), new ItemStack(WTItems.itemJug_2), new ItemStack(WTItems.itemJug_2));
				r.addShapeless(new ItemStack(WTItems.itemJug_6), new ItemStack(WTItems.itemJug_4), new ItemStack(WTItems.itemJug_2));
				r.addShapeless(new ItemStack(WTItems.itemJug_12), new ItemStack(WTItems.itemJug_6), new ItemStack(WTItems.itemJug_6));
				r.addShapeless(new ItemStack(WTItems.itemJug_12), new ItemStack(WTItems.itemJug_4), new ItemStack(WTItems.itemJug_4), new ItemStack(WTItems.itemJug_4));
				r.addShapeless(new ItemStack(WTItems.itemJug_24), new ItemStack(WTItems.itemJug_6), new ItemStack(WTItems.itemJug_6), new ItemStack(WTItems.itemJug_6), new ItemStack(WTItems.itemJug_6));
				r.addShapeless(new ItemStack(WTItems.itemJug_24), new ItemStack(WTItems.itemJug_12), new ItemStack(WTItems.itemJug_12));
				r.addShapeless(new ItemStack(WTItems.itemJug_48), new ItemStack(WTItems.itemJug_12), new ItemStack(WTItems.itemJug_12), new ItemStack(WTItems.itemJug_12), new ItemStack(WTItems.itemJug_12));
				r.addShapeless(new ItemStack(WTItems.itemJug_48), new ItemStack(WTItems.itemJug_24), new ItemStack(WTItems.itemJug_24));
				r.addBasicMachineRecipe(WurmTweaksItems.creativeCreativeParts, new ItemStack(LudicrousBlocks.resource_block, 1, 1), WurmTweaksItems.itemAntiMatter, new ItemStack(LudicrousBlocks.resource_block, 1, 0), new ItemStack(BigReactors.blockMetal, 1, 4));
				r.addCrossWCenter(WurmTweaksItems.creativeCreativePartsEnergy, WurmTweaksBlocks.blockCompressedRedstone, new ItemStack(LudicrousItems.resource, 1, 5), WurmTweaksItems.creativeCreativeParts);
				r.addShapeless(new ItemStack(Blocks.redstone_block, 4), new ItemStack(WurmTweaksBlocks.blockCompressedRedstone));
				r.addShaped(new ItemStack(WTItems.itemPill, 2, 0), "RFR", "RFR", "RFR", 'R', "packRubber", 'F', WurmTweaksItems.foodFruit);
				r.addShaped(new ItemStack(WTItems.itemPill, 2, 1), "RFR", "RFR", "RFR", 'R', "packRubber", 'F', WurmTweaksItems.foodGrain);
				r.addShaped(new ItemStack(WTItems.itemPill, 2, 2), "RFR", "RFR", "RFR", 'R', "packRubber", 'F', WurmTweaksItems.foodMeat);
				r.addShaped(new ItemStack(WTItems.itemPill, 2, 3), "RFR", "RFR", "RFR", 'R', "packRubber", 'F', WurmTweaksItems.foodVegtable);
				r.addShaped(new ItemStack(WTItems.itemPill, 2, 4), "RFR", "RFR", "RFR", 'R', "packRubber", 'F', WurmTweaksItems.foodCheese);
				r.addShaped(new ItemStack(WTItems.itemPill, 2, 5), "RFR", "RFR", "RFR", 'R', "packRubber", 'F', WurmTweaksItems.foodGods);
				r.addShapeless(new ItemStack(WTItems.itemPill, 5, 5), new ItemStack(WTItems.itemPill, 1, 0), new ItemStack(WTItems.itemPill, 1, 1), new ItemStack(WTItems.itemPill, 1, 2), new ItemStack(WTItems.itemPill, 1, 3), new ItemStack(WTItems.itemPill, 1, 4));
				r.addShaped(new ItemStack(WTItems.helmetDarkMatter), "MMM", "MHM", 'M', WurmTweaksItems.itemDarkMatter, 'H', LudicrousItems.infinity_helm);
				r.addShaped(new ItemStack(WTItems.helmetRedMatter), "MMM", "MHM", 'M', WurmTweaksItems.itemRedMatter, 'H', WTItems.helmetDarkMatter);
				r.addShaped(new ItemStack(WTItems.chestDarkMatter), "MCM", "MMM", "MMM", 'M', WurmTweaksItems.itemDarkMatter, 'C', LudicrousItems.infinity_armor);
				r.addShaped(new ItemStack(WTItems.chestRedMatter), "MCM", "MMM", "MMM", 'M', WurmTweaksItems.itemRedMatter, 'C', WTItems.chestDarkMatter);
				r.addShaped(new ItemStack(WTItems.leggsDarkMatter), "MMM", "MLM", "M M", 'M', WurmTweaksItems.itemDarkMatter, 'L', LudicrousItems.infinity_pants);
				r.addShaped(new ItemStack(WTItems.leggsRedMatter), "MMM", "MLM", "M M", 'M', WurmTweaksItems.itemRedMatter, 'L', WTItems.leggsDarkMatter);
				r.addShaped(new ItemStack(WTItems.bootsDarkMatter), "M M", "MBM", 'M', WurmTweaksItems.itemDarkMatter, 'B', LudicrousItems.infinity_shoes);
				r.addShaped(new ItemStack(WTItems.bootsRedMatter), "M M", "MBM", 'M', WurmTweaksItems.itemRedMatter, 'B', WTItems.bootsDarkMatter);
				r.addShaped9X9Recipe(WurmTweaksItems.itemDarkMatter, "ABBBBBBBA", "BXXXXXXXB","BXCCCCCXB", "BXCFFFCXB", "BXCFFFCXB", "BXCFFFCXB", "BXCCCCCXB", "BXXXXXXXB", "ABBBBBBBA", 'A', new ItemStack(LudicrousItems.resource, 1, 5), 'B', new ItemStack(LudicrousBlocks.resource_block, 1, 1), 'X', "packGemBlock", 'C', new ItemStack(AdvancedSolarPanel.blockAdvSolarPanel, 1, 3), 'F', new ItemStack(TEBlocks.blockCell, 1, 0));
				r.addShaped(WurmTweaksItems.itemRedMatter, "XAX", "AXA", "XAX", 'X', WurmTweaksItems.itemDarkMatter, 'A', WurmTweaksItems.creativeCreativeParts);
				addCompressor();
		}

		private static void addCompressor () {
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.wroughtIronIngot, 32), new ItemStack(WurmTweaksBlocks.blockWroughtIron));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.platinumIngot, 32), new ItemStack(WurmTweaksBlocks.blockPlatinum));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.goldIngot, 32), new ItemStack(WurmTweaksBlocks.blockGold));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.sterlingSilverIngot, 32), new ItemStack(WurmTweaksBlocks.blockSterlingSilver));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.silverIngot, 32), new ItemStack(WurmTweaksBlocks.blockSilver));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.blueSteelIngot, 32), new ItemStack(WurmTweaksBlocks.blockBlueSteel));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.blackSteelIngot, 32), new ItemStack(WurmTweaksBlocks.blockBlackSteel));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.redSteelIngot, 32), new ItemStack(WurmTweaksBlocks.blockRedSteel));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.copperIngot, 32), new ItemStack(WurmTweaksBlocks.blockCopper));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.steelIngot, 32), new ItemStack(WurmTweaksBlocks.blockSteel));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.bronzeIngot, 32), new ItemStack(WurmTweaksBlocks.blockBronze));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.bismuthIngot, 32), new ItemStack(WurmTweaksBlocks.blockBismuth));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.bismuthBronzeIngot, 32), new ItemStack(WurmTweaksBlocks.blockBismuthBronze));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.blackBronzeIngot, 32), new ItemStack(WurmTweaksBlocks.blockBlackBronze));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.brassIngot, 32), new ItemStack(WurmTweaksBlocks.blockBrass));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.leadIngot, 32), new ItemStack(WurmTweaksBlocks.blockLead));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.nickelIngot, 32), new ItemStack(WurmTweaksBlocks.blockNickel));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.pigIronIngot, 32), new ItemStack(WurmTweaksBlocks.blockPigIron));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.roseGoldIngot, 32), new ItemStack(WurmTweaksBlocks.blockRoseGold));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.zincIngot, 32), new ItemStack(WurmTweaksBlocks.blockZinc));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.tinIngot, 32), new ItemStack(WurmTweaksBlocks.blockTin));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.unknownIngot, 32), new ItemStack(WurmTweaksBlocks.blockUnkown));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemJasper, 32, 4), new ItemStack(WurmTweaksBlocks.blockJasper));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemAmethyst, 32, 4), new ItemStack(WurmTweaksBlocks.blockAmethyst));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemDiamond, 32, 4), new ItemStack(WurmTweaksBlocks.blockDiamond));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemRuby, 32, 4), new ItemStack(WurmTweaksBlocks.blockRuby));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemSapphire, 32, 4), new ItemStack(WurmTweaksBlocks.blockSapphire));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemEmerald, 32, 4), new ItemStack(WurmTweaksBlocks.blockEmerald));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemTopaz, 32, 4), new ItemStack(WurmTweaksBlocks.blockTopaz));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemTourmaline, 32, 4), new ItemStack(WurmTweaksBlocks.blockTourmaline));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemJade, 32, 4), new ItemStack(WurmTweaksBlocks.blockJade));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemAgate, 32, 4), new ItemStack(WurmTweaksBlocks.blockAgate));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemOpal, 32, 4), new ItemStack(WurmTweaksBlocks.blockOpal));
				ICHelper.addCompressorRecipe(new ItemStack(TFCItems.gemGarnet, 32, 4), new ItemStack(WurmTweaksBlocks.blockGarnet));
				ICHelper.addCompressorRecipe(new ItemStack(Blocks.redstone_block, 4), new ItemStack(WurmTweaksBlocks.blockCompressedRedstone));
		}
}
