package wurmcraft.wurmatron.common.recipes.mods;

import com.bioxx.tfc.api.TFCBlocks;
import com.bioxx.tfc.api.TFCItems;
import com.riciJak.Ztones.init.ModBlocks;
import com.riciJak.Ztones.init.ModItems;
import cpw.mods.fml.common.Optional;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;
import wurmcraft.wurmatron.common.blocks.WurmTweaksBlocks;
import wurmcraft.wurmatron.common.items.WurmTweaksItems;
import wurmcraft.wurmatron.common.recipes.RecipeHelper;
import wurmcraft.wurmatron.common.utils.LogHandler;

public class ZTonesRecipes {

		private static final RecipeHelper r = new RecipeHelper();

		@Optional.Method (modid = "Ztones")
		public static void addRecipes () {
				LogHandler.info("Adding Ztones Recipes");
				r.addShaped(ModItems.ofanix, "ABC", "BDB", "EBF", 'A', Items.ender_pearl, 'B', TFCItems.wroughtIronIngot, 'C', TFCItems.blueSteelBucketLava, 'D', "packCraftingTable", 'E', TFCItems.redSteelBucketWater, 'F', "packGem");
				r.addShaped(ModItems.ofanix, "ABC", "BDB", "EBF", 'A', Items.ender_pearl, 'B', TFCItems.wroughtIronIngot, 'C', TFCItems.blueSteelBucketLava, 'D', "packCraftingTable", 'E', TFCItems.redSteelBucketSaltWater, 'F', "packGem");
				r.addShaped(ModBlocks.stoneTile, "AA ", "ABA", " AA", 'A', "packCobblestone", 'B', "packSmoothStone");
				r.addShaped(ModBlocks.cleanDirt, "AAA", "ABC", "CCC", 'A', "packDirt", 'B', "packSeed", 'C', "packSand");
				r.addShaped(ModBlocks.booster, "AA", 'A', WurmTweaksBlocks.blockCompressedRedstone);
				r.addCrossWCenter(ModBlocks.lampf, TFCItems.wroughtIronIngot, "packGlass", Items.glowstone_dust);
				r.addShapeless(ModBlocks.lampb, ModBlocks.lampf);
				r.addShapeless(ModBlocks.lampt, ModBlocks.lampb);
				r.addShaped(ModBlocks.auroraBlock, "AA ", "ABA", " AA", 'A', "packGlass", 'B', "dyeBlack");
				// Agon Block Set
				r.addCircleWCenter(ModBlocks.agonBlock, ModBlocks.stoneTile, ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.auroraBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.agonBlock);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.agonBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.agonBlock, 'B', ModItems.ofanix);
				// Bitt Block Set
				r.addCircleWCenter(ModBlocks.bittBlock, ModBlocks.stoneTile, new ItemStack(Blocks.wool, 1, OreDictionary.WILDCARD_VALUE));
				r.addShaped(ModBlocks.bittBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.bittBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.bittBlock, 'B', ModItems.ofanix);
				// Cray Block Set
				r.addCircleWCenter(ModBlocks.crayBlock, Blocks.hardened_clay, ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.crayBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.bittBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.crayBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.crayBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.crayBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.crayBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.crayBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.crayBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.crayBlock);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.crayBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.crayBlock, 'B', ModItems.ofanix);
				// Fort Block Set
				r.addCircleWCenter(ModBlocks.fortBlock, ModBlocks.ztylBlock, ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.fortBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.fortBlock);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.fortBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.fortBlock, 'B', ModItems.ofanix);
				// Iszm Block Set
				r.addCircleWCenter(ModBlocks.iszmBlock, new ItemStack(ModBlocks.ztylBlock, 1, 8), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.iszmBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.iszmBlock);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.iszmBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.iszmBlock, 'B', ModItems.ofanix);
				// Jelt Block Set
				r.addCircleWCenter(ModBlocks.jeltBlock, ModBlocks.stoneTile, TFCItems.goldIngot);
				r.addShaped(ModBlocks.jeltBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.jeltBlock);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.jeltBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.jeltBlock, 'B', ModItems.ofanix);
				// Korp Block Set
				r.addCircleWCenter(ModBlocks.korpBlock, ModBlocks.stoneTile, Blocks.obsidian);
				r.addShaped(ModBlocks.korpBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.korpBlock);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.korpBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.korpBlock, 'B', ModItems.ofanix);
				// Kryp Block Set
				r.addCircleWCenter(ModBlocks.krypBlock, ModBlocks.stoneTile, "packSand");
				r.addShaped(ModBlocks.krypBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.krypBlock);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.krypBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.krypBlock, 'B', ModItems.ofanix);
				// Lair Block Set
				r.addCircleWCenter(ModBlocks.lairBlock, ModBlocks.stoneTile, "packLog");
				r.addShaped(ModBlocks.lairBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.lairBlock);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.lairBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.lairBlock, 'B', ModItems.ofanix);
				// Lave Block Set
				r.addCircleWCenter(ModBlocks.laveBlock, ModBlocks.stoneTile, TFCBlocks.ice);
				r.addShaped(ModBlocks.laveBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.laveBlock);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.laveBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.laveBlock, 'B', ModItems.ofanix);
				// Mint Block Set
				r.addCircleWCenter(ModBlocks.mintBlock, ModBlocks.stoneTile, Items.slime_ball);
				r.addShaped(ModBlocks.mintBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.mintBlock);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mintBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.mintBlock, 'B', ModItems.ofanix);
				// Myst Block Set
				r.addCircleWCenter(new ItemStack(ModBlocks.mystBlock, 48), "packSmoothStone", WurmTweaksItems.ingotGraySteel);
				r.addShaped(ModBlocks.mystBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.mystBlock);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.mystBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.mystBlock, 'B', ModItems.ofanix);
				// Reds Block Set
				r.addCircleWCenter(ModBlocks.redsBlock, ModBlocks.stoneTile, Items.redstone);
				r.addShaped(ModBlocks.redsBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.redsBlock);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.redsBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.redsBlock, 'B', ModItems.ofanix);
				// Roen Block Set
				r.addCircleWCenter(ModBlocks.roenBlock, ModBlocks.stoneTile, "dyeYellow");
				r.addShaped(ModBlocks.roenBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.roenBlock);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.roenBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.roenBlock, 'B', ModItems.ofanix);
				// Sols Block Set
				r.addCircleWCenter(ModBlocks.solsBlock, ModBlocks.stoneTile, new ItemStack(TFCItems.powder, 1, 3));
				r.addShaped(ModBlocks.solsBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.solsBlock);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.solsBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.solsBlock, 'B', ModItems.ofanix);
				// Tank Block Set
				r.addCircleWCenter(ModBlocks.tankBlock, ModBlocks.stoneTile, TFCItems.wroughtIronIngot);
				r.addShaped(ModBlocks.tankBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.tankBlock);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.tankBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.tankBlock, 'B', ModItems.ofanix);
				// Vect Block Set
				r.addCircleWCenter(ModBlocks.vectBlock, ModBlocks.stoneTile, "dyeGray");
				r.addShaped(ModBlocks.vectBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.vectBlock);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.vectBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.vectBlock, 'B', ModItems.ofanix);
				// Vena Block Set
				r.addCircleWCenter(ModBlocks.venaBlock, ModBlocks.stoneTile, Items.ender_pearl);
				r.addShaped(ModBlocks.venaBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.venaBlock);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.venaBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.venaBlock, 'B', ModItems.ofanix);
				// Zech Block Set
				r.addCircleWCenter(ModBlocks.zechBlock, new ItemStack(ModBlocks.ztylBlock, 1, 4), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zechBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zechBlock);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zechBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zechBlock, 'B', ModItems.ofanix);
				// Zion Block Set
				r.addCircleWCenter(ModBlocks.zionBlock, new ItemStack(ModBlocks.ztylBlock, 1, 7), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zionBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zionBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zionBlock, 'B', ModItems.ofanix);
				// Zome Block Set
				r.addCircleWCenter(ModBlocks.zomeBlock, new ItemStack(ModBlocks.ztylBlock, 1, 6), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zomeBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zionBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zomeBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zomeBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zomeBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zomeBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zomeBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zomeBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zomeBlock);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zomeBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zomeBlock, 'B', ModItems.ofanix);
				// Zone Block Set
				r.addCircleWCenter(ModBlocks.zoneBlock, new ItemStack(ModBlocks.ztylBlock, 1, 3), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zoneBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zoneBlock);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoneBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zoneBlock, 'B', ModItems.ofanix);
				// Zorg Block Set
				r.addCircleWCenter(ModBlocks.zorgBlock, new ItemStack(ModBlocks.ztylBlock, 1, 5), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zorgBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zorgBlock);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zorgBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zorgBlock, 'B', ModItems.ofanix);
				// Tinted Glass Block Set
				r.addCircleWCenter(ModBlocks.glaxx, "packGlass", ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.glaxx, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.glaxx);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.glaxx, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.glaxx, 'B', ModItems.ofanix);
				// Reed Block Set
				r.addCircleWCenter(ModBlocks.reedBlock, ModBlocks.stoneTile, TFCItems.sugarcane);
				r.addCircleWCenter(ModBlocks.reedBlock, ModBlocks.stoneTile, Blocks.reeds);
				r.addShaped(ModBlocks.reedBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.reedBlock);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.reedBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.reedBlock, 'B', ModItems.ofanix);
				// Sync Block Set
				r.addCircleWCenter(ModBlocks.syncBlock, ModBlocks.stoneTile, TFCItems.gemEmerald);
				r.addCircleWCenter(ModBlocks.syncBlock, ModBlocks.stoneTile, Items.emerald);
				r.addShaped(ModBlocks.syncBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.syncBlock);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.syncBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.syncBlock, 'B', ModItems.ofanix);
				// Zkul Block Set
				r.addCircleWCenter(ModBlocks.zkulBlock, new ItemStack(ModBlocks.ztylBlock, 1, 10), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zkulBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zkulBlock);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zkulBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zkulBlock, 'B', ModItems.ofanix);
				// Azur Block Set
				r.addCircleWCenter(ModBlocks.azurBlock, ModBlocks.stoneTile, "dyeBlue");
				r.addShaped(ModBlocks.azurBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.azurBlock);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.azurBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.azurBlock, 'B', ModItems.ofanix);
				// Zeta Block Set
				r.addCircleWCenter(ModBlocks.zetaBlock, new ItemStack(ModBlocks.ztylBlock, 1, 13), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zetaBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zetaBlock);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zetaBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zetaBlock, 'B', ModItems.ofanix);
				// Zest Block Set
				r.addCircleWCenter(ModBlocks.zestBlock, new ItemStack(ModBlocks.ztylBlock, 1, 11), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zestBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zestBlock);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zestBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zestBlock, 'B', ModItems.ofanix);
				// Zoea Block Set
				r.addCircleWCenter(ModBlocks.zoeaBlock, new ItemStack(ModBlocks.ztylBlock, 1, 14), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zoeaBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zoeaBlock);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zoeaBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zoeaBlock, 'B', ModItems.ofanix);
				// Zane Block Set
				r.addCircleWCenter(ModBlocks.zaneBlock, new ItemStack(ModBlocks.ztylBlock, 1, 12), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zaneBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zaneBlock);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zaneBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zaneBlock, 'B', ModItems.ofanix);
				// Zyth Block Set
				r.addCircleWCenter(ModBlocks.zythBlock, new ItemStack(ModBlocks.ztylBlock, 1, 15), ModBlocks.auroraBlock);
				r.addShaped(ModBlocks.zythBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.zythBlock);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.zythBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.zythBlock, 'B', ModItems.ofanix);
				// Ztyl Block Set
				r.addShaped(ModBlocks.ztylBlock, "AAA", "BAC", "AAA", 'A', ModBlocks.stoneTile, 'B', Blocks.coal_block, 'C', TFCItems.wroughtIronIngot2x);
				r.addShaped(ModBlocks.ztylBlock, "AB ", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 1), "A B", "   ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 2), "A  ", "B  ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 3), "A  ", " B ", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 4), "A  ", "  B", "   ", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 5), "A  ", "   ", "B  ", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 6), "A  ", "   ", " B ", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 7), "A  ", "   ", "  B", 'A', ModItems.ofanix, 'B', ModBlocks.ztylBlock);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 8), "A  ", "   ", "  B", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 9), " A ", "   ", "  B", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 10), "  A", "   ", "  B", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 11), "   ", "A  ", "  B", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 12), "   ", " A ", "  B", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 13), "   ", "  A", "  B", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 14), "   ", "   ", "A B", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
				r.addShaped(new ItemStack(ModBlocks.ztylBlock, 1, 15), "   ", "   ", " AB", 'A', ModBlocks.ztylBlock, 'B', ModItems.ofanix);
		}
}
